"""
Coverage for the plain-language "why was this blocked" summary (P2 item 7
of the WAAP console teardown roadmap).
"""
import pytest
from types import SimpleNamespace

from app.services.threat_explain import _score_breakdown, generate_plain_explanation


# Reference input/output pairs generated by actually running
# ml-waf/threat_score.py's calculate_threat_score() during development
# (see this file's own module docstring) — pins _score_breakdown as a
# faithful port, so the two containers' scoring math can't silently drift
# apart without a test failing.
@pytest.mark.parametrize("inputs,expected", [
    ((15.0, 0.62, -0.31, 3, 0), {"total": 0.7749999999999999, "crs": 0.75, "xgb": 0.62, "iso": 0.62, "reputation": 0.09}),
    ((0, 0.85, 0.1, 0, 0), {"total": 0.255, "crs": 0.0, "xgb": 0.85, "iso": 0.0, "reputation": 0.0}),
    ((20, 0, 0, 0, 0), {"total": 0.5, "crs": 1.0, "xgb": 0.0, "iso": -0.0, "reputation": 0.0}),
    ((0, 0, 0, 10, 100), {"total": 0.3, "crs": 0.0, "xgb": 0.0, "iso": -0.0, "reputation": 0.3}),
    ((5, 0.4, -0.1, 1, 20), {"total": 0.3450000000000001, "crs": 0.25, "xgb": 0.4, "iso": 0.2, "reputation": 0.06}),
])
def test_score_breakdown_matches_ml_waf_reference_values(inputs, expected):
    assert _score_breakdown(*inputs) == expected


def _waf_event(attack_type="SQL Injection", rule_id="942100", message="SQL Injection Attack Detected"):
    return SimpleNamespace(attack_type=attack_type, rule_id=rule_id, message=message)


def _ml_event(crs_score=0.0, xgb_prob=0.0, iso_score=0.0, redis_rep=0.0, abuse_score=0.0):
    return SimpleNamespace(crs_score=crs_score, xgb_prob=xgb_prob, iso_score=iso_score, redis_rep=redis_rep, abuse_score=abuse_score)


def test_no_ml_event_still_explains_the_rule_match():
    """Most blocks never reach ML scoring (ModSecurity blocks natively) —
    the summary must still say something useful, not go blank."""
    summary = generate_plain_explanation(_waf_event(), None)
    assert "SQL Injection" in summary
    assert "942100" in summary
    assert "SQL Injection Attack Detected" in summary


def test_missing_rule_id_falls_back_to_the_message_alone():
    summary = generate_plain_explanation(_waf_event(rule_id="", message="Anomaly threshold exceeded"), None)
    assert "Anomaly threshold exceeded" in summary
    assert "()" not in summary  # no dangling empty parens when rule_id is blank


def test_unknown_attack_type_does_not_claim_a_specific_category():
    """Never state a specific attack type the data doesn't actually support
    — 'Unknown' is itself a real signal, not something to paper over."""
    summary = generate_plain_explanation(_waf_event(attack_type="Unknown"), None)
    assert "Unknown attempt" not in summary
    assert "WAF rule engine" in summary


def test_crs_dominant_names_the_rule_engine_as_primary_driver():
    summary = generate_plain_explanation(_waf_event(), _ml_event(crs_score=18, xgb_prob=0.1, iso_score=0, redis_rep=0))
    assert "OWASP Core Rule Set" in summary
    assert "ML classifier" not in summary  # xgb's contribution here is too small to mention


def test_xgb_dominant_states_the_classifier_confidence_as_a_percentage():
    summary = generate_plain_explanation(_waf_event(), _ml_event(crs_score=0, xgb_prob=0.9, iso_score=0, redis_rep=0))
    assert "90% likely malicious" in summary


def test_reputation_dominant_cites_the_ip_history():
    summary = generate_plain_explanation(_waf_event(), _ml_event(crs_score=0, xgb_prob=0, iso_score=0, redis_rep=5, abuse_score=0))
    assert "history of prior blocks" in summary


def test_second_factor_only_mentioned_when_its_contribution_is_meaningful():
    # xgb dominant (0.9 * 0.30 = 0.27); crs second but tiny (2/20 * 0.50 = 0.05) — below the 0.15 threshold to mention.
    summary = generate_plain_explanation(_waf_event(), _ml_event(crs_score=2, xgb_prob=0.9, iso_score=0, redis_rep=0))
    assert "amplified by" not in summary

    # xgb dominant (0.9 * 0.30 = 0.27); crs second and substantial (16/20 * 0.50 = 0.40 — wait this would make crs
    # dominant instead, so use a case where xgb stays on top: crs=6 -> 6/20*0.50=0.15, right at the threshold.
    summary2 = generate_plain_explanation(_waf_event(), _ml_event(crs_score=6, xgb_prob=0.9, iso_score=0, redis_rep=0))
    assert "amplified by" in summary2


def test_all_components_near_zero_omits_the_ml_sentence_entirely():
    """An ml_event that matched but scored ~clean shouldn't invent a
    'primary driver' out of noise."""
    summary = generate_plain_explanation(_waf_event(), _ml_event(crs_score=0, xgb_prob=0, iso_score=0, redis_rep=0))
    assert "driven by" not in summary
    assert "SQL Injection" in summary  # the rule-match sentence is still there
