import os
import re
import subprocess
import ipaddress
import logging
import redis

logger = logging.getLogger(__name__)

DDOS_CONF_PATH = "/etc/nginx/conf.d/waf_ddos.conf"
HARDENING_CONF_PATH = "/etc/nginx/conf.d/waf_hardening.conf"
REDIS_SECRET_FILE = "/etc/cybersentinel/redis.secret"  # nosec B105


def _get_redis_password() -> str:
    """
    Reads the Redis authentication password from a protected secret file.
    Falls back to empty string (no auth) if the file does not exist.
    """
    try:
        with open(REDIS_SECRET_FILE, "r") as f:
            return f.read().strip()
    except FileNotFoundError:
        logger.warning(
            f"Redis secret file not found at {REDIS_SECRET_FILE}. "
            "Connecting without authentication."
        )
        return ""
    except Exception as e:
        logger.error(f"Failed to read Redis secret file: {e}")
        return ""


def _sanitize_nginx_pattern(value: str) -> str:
    """
    Strips characters that would break NGINX map block structure or allow
    arbitrary directive injection via user-supplied rate limiting patterns.
    Removes: { } ; newlines and carriage returns.
    """
    return re.sub(r'[{};\'"\n\r]', '', value)


def _validate_ip_or_cidr(ip: str) -> bool:
    """
    Validates that a string is a valid IPv4/IPv6 address or CIDR network.
    Returns True if valid, False otherwise.
    """
    try:
        ipaddress.ip_network(ip.strip(), strict=False)
        return True
    except ValueError:
        return False


def apply_ddos_settings(settings: dict) -> bool:
    """
    Generates NGINX rate-limiting configuration based on the provided settings
    and reloads NGINX to apply them.
    """
    try:
        rate_limit_rps = settings.get("rate_limit_rps", 50)
        burst_tolerance = settings.get("burst_tolerance", 100)
        trusted_ips = settings.get("trusted_ips", [])
        bot_action = settings.get("bot_mitigation_action", "Silent Drop")
        advanced_rules = settings.get("advanced_rules", [])

        # Determine HTTP status code based on bot_action
        # Silent Drop -> 444 (NGINX special code to close connection)
        # Block -> 429 (Too Many Requests) or 503 (Service Unavailable)
        status_code = 444 if bot_action == "Silent Drop" else 429

        config_lines = [
            "# Auto-generated by CyberSentinel WAF GUI",
            "# Do not edit manually",
            "",
        ]

        # Define GeoIP2 databases if they exist on disk.
        # GEOIP_DATA_DIR env var allows portable deployment on client servers.
        # Falls back to the demo-server absolute path when env var is not set.
        _geoip_dir = os.environ.get(
            "GEOIP_DATA_DIR",
            os.path.abspath(
                os.path.join(os.path.dirname(os.path.dirname(__file__)), "data")
            )
        )
        COUNTRY_DB = os.path.join(_geoip_dir, "GeoLite2-Country.mmdb")
        ASN_DB = os.path.join(_geoip_dir, "GeoLite2-ASN.mmdb")

        has_country_db = os.path.exists(COUNTRY_DB)
        has_asn_db = os.path.exists(ASN_DB)

        if has_country_db:
            config_lines.append(f"geoip2 {COUNTRY_DB} {{")
            config_lines.append(
                "    $geoip2_data_country_code source=$remote_addr country iso_code;"
            )
            config_lines.append("}")
            config_lines.append("")

        if has_asn_db:
            config_lines.append(f"geoip2 {ASN_DB} {{")
            config_lines.append(
                "    $geoip2_data_asn source=$remote_addr autonomous_system_number;"
            )
            config_lines.append(
                "    $geoip2_data_org source=$remote_addr autonomous_system_organization;"
            )
            config_lines.append("}")
            config_lines.append("")

        # --- Bot Mitigation ---
        config_lines.append("# --- Bot Mitigation ---")
        config_lines.append("map $http_user_agent $is_bad_bot {")
        config_lines.append("    default 0;")
        # Malicious crawlers & scrapers
        config_lines.append('    "~*semrush" 1;')
        config_lines.append('    "~*ahrefs" 1;')
        config_lines.append('    "~*mj12bot" 1;')
        config_lines.append('    "~*dotbot" 1;')
        config_lines.append('    "~*rogerbot" 1;')
        config_lines.append('    "~*megaindex" 1;')
        config_lines.append('    "~*zoominfobot" 1;')
        config_lines.append('    "~*yandexbot" 1;')
        config_lines.append('    "~*baiduspider" 1;')
        config_lines.append('    "~*screaming frog" 1;')
        # Vulnerability scanners & tools
        config_lines.append('    "~*sqlmap" 1;')
        config_lines.append('    "~*nmap" 1;')
        config_lines.append('    "~*nikto" 1;')
        config_lines.append('    "~*dirbuster" 1;')
        config_lines.append('    "~*censys" 1;')
        config_lines.append('    "~*shodan" 1;')
        config_lines.append('    "~*netsparker" 1;')
        config_lines.append('    "~*acunetix" 1;')
        # Common HTTP client libraries used for botting
        config_lines.append('    "~*python-requests" 1;')
        config_lines.append('    "~*pycurl" 1;')
        config_lines.append('    "~*urllib" 1;')
        config_lines.append('    "~*wget" 1;')
        # Empty user-agent or standard hyphen
        config_lines.append('    "-" 1;')
        config_lines.append('    "" 1;')
        config_lines.append("}")
        config_lines.append("")
        config_lines.append("map $is_bad_bot $bot_limit_key {")
        config_lines.append('    0 "";')
        config_lines.append('    1 "bad_bot_key";')
        config_lines.append("}")
        config_lines.append("")
        # We define a dedicated rate limiting zone for bad bots.
        # It permits 1 request per minute globally for all bad bots (effectively blocking them completely).
        config_lines.append("limit_req_zone $bot_limit_key zone=waf_bot_req:10m rate=1r/m;")
        config_lines.append("")

        # We always define the $limit_key variable.
        # If trusted_ips exist, it is dynamic. If not, it is equivalent to $binary_remote_addr.
        if trusted_ips:
            config_lines.append("geo $limit {")
            config_lines.append("    default 1;")
            for ip in trusted_ips:
                ip = ip.strip()
                if ip:
                    if not _validate_ip_or_cidr(ip):
                        logger.warning(f"Skipping invalid IP/CIDR in trusted list: '{ip}'")
                        continue
                    config_lines.append(f"    {ip} 0;")
            config_lines.append("")
            config_lines.append("map $limit $limit_key {")
            config_lines.append('    0 "";')
            config_lines.append("    1 $binary_remote_addr;")
            config_lines.append("}")
        else:
            config_lines.append("map $host $limit_key {")
            config_lines.append("    default $binary_remote_addr;")
            config_lines.append("}")

        config_lines.append("")
        zone_key = "$limit_key"

        config_lines.append(
            f"limit_req_zone {zone_key} zone=waf_ddos_req:10m rate={rate_limit_rps}r/s;"
        )
        config_lines.append(f"limit_req_status {status_code};")
        config_lines.append("")
        # Apply globally to all traffic in the HTTP context
        config_lines.append(
            f"limit_req zone=waf_ddos_req burst={burst_tolerance} nodelay;"
        )
        # Apply bot mitigation rate-limiting globally
        # burst=1 because nginx requires burst >= 1; bots hit limit=1r/m so burst of 1 is effectively immediate block
        config_lines.append("limit_req zone=waf_bot_req burst=1 nodelay;")
        config_lines.append("")

        # Connection limiting
        config_lines.append(f"limit_conn_zone {zone_key} zone=waf_ddos_conn:10m;")
        config_lines.append(f"limit_conn_status {status_code};")
        config_lines.append(
            "limit_conn waf_ddos_conn 100;"
        )  # Hardcoded max 100 connections per IP for now
        config_lines.append("")

        # --- Advanced Rate Limiting Rules ---
        if advanced_rules:
            config_lines.append("# --- Advanced Rate Limiting Rules ---")
            for rule in advanced_rules:
                if not rule.get("enabled", True):
                    continue
                rule_id = rule.get("id")
                rule_name = rule.get("name", f"Rule {rule_id}")
                param_type = rule.get("parameter_type", "URI")
                param_value = rule.get("parameter_value", "")
                rule_rps = rule.get("rate_limit_rps", 10)
                rule_burst = rule.get("burst_tolerance", 20)

                # Determine NGINX variable to inspect and whether to rate-limit by the value itself
                nginx_var = "$request_uri"
                limit_by_value = False
                if param_type == "URI":
                    nginx_var = "$request_uri"
                elif param_type == "Method":
                    nginx_var = "$request_method"
                elif param_type == "Referrer":
                    nginx_var = "$http_referer"
                elif param_type == "Content-Type":
                    nginx_var = "$http_content_type"
                elif param_type == "IP":
                    nginx_var = "$remote_addr"
                elif param_type == "Session":
                    cookie_name = param_value.strip() or "session"
                    nginx_var = f"$cookie_{cookie_name.lower().replace('-', '_')}"
                    limit_by_value = True
                elif param_type == "Country":
                    if not has_country_db:
                        logger.warning(
                            f"Skipping Country rate limiting rule '{rule_name}' because Country GeoIP DB is missing."
                        )
                        continue
                    nginx_var = "$geoip2_data_country_code"
                elif param_type == "ISP/ASN":
                    if not has_asn_db:
                        logger.warning(
                            f"Skipping ISP/ASN rate limiting rule '{rule_name}' because ASN GeoIP DB is missing."
                        )
                        continue
                    # Match ASN (if numeric) or Org name
                    if param_value.strip().isdigit():
                        nginx_var = "$geoip2_data_asn"
                    else:
                        nginx_var = "$geoip2_data_org"
                elif param_type == "Header":
                    # Custom header parsing (e.g. "X-API-Key: value" or just "X-API-Key")
                    if ":" in param_value:
                        parts = param_value.split(":", 1)
                        header_name = parts[0].strip()
                        param_value = parts[1].strip()
                        nginx_var = "$http_" + header_name.lower().replace("-", "_")
                    else:
                        header_name = param_value.strip()
                        nginx_var = "$http_" + header_name.lower().replace("-", "_")
                        limit_by_value = True

                if limit_by_value:
                    config_lines.append(
                        f"# Rule: {rule_name} (Type: {param_type}, Limit by unique value of {nginx_var})"
                    )
                    config_lines.append(f"map {nginx_var} $limit_key_{rule_id} {{")
                    config_lines.append(f'    "~.+" {nginx_var};')
                    config_lines.append('    default "";')
                    config_lines.append("}")
                else:
                    # Sanitize pattern to prevent NGINX config injection
                    # Strip characters that can break NGINX map block structure
                    clean_value = _sanitize_nginx_pattern(param_value)
                    if not clean_value:
                        logger.warning(f"Skipping rule '{rule_name}': pattern is empty after sanitization.")
                        continue

                    config_lines.append(
                        f"# Rule: {rule_name} (Type: {param_type}, Match: {param_value})"
                    )
                    config_lines.append(f"map {nginx_var} $limit_key_{rule_id} {{")
                    # Map to $limit_key (so trusted IPs automatically bypass this check)
                    # If param_type is Country, IP or numeric ISP/ASN, anchor matching with ^...$ to prevent substring matching
                    if param_type in ("Country", "IP") or (param_type == "ISP/ASN" and param_value.strip().isdigit()):
                        config_lines.append(f'    "~*^{clean_value}$" {zone_key};')
                    else:
                        config_lines.append(f'    "~*{clean_value}" {zone_key};')
                    config_lines.append('    default "";')
                    config_lines.append("}")

                config_lines.append(
                    f"limit_req_zone $limit_key_{rule_id} zone=zone_{rule_id}:10m rate={rule_rps}r/s;"
                )
                config_lines.append(
                    f"limit_req zone=zone_{rule_id} burst={rule_burst} nodelay;"
                )
                config_lines.append("")

        config_content = "\n".join(config_lines) + "\n"

        # Since the backend runs as root (via sudo), it can write directly
        with open(DDOS_CONF_PATH, "w", encoding="utf-8") as f:
            f.write(config_content)

        logger.info(f"Successfully generated NGINX DDoS config at {DDOS_CONF_PATH}")

        # Reload NGINX to apply
        return reload_nginx()

    except Exception as e:
        logger.error(f"Failed to apply DDoS settings: {e}")
        return False


def reload_nginx() -> bool:
    """
    Reloads the NGINX/OpenResty service gracefully.
    Tries sudo-prefixed commands first (required when running as non-root service user).
    Falls back to direct execution if sudo is not available.
    Requires /etc/sudoers.d/cybersentinel-waf to grant NOPASSWD for these commands.
    """
    candidates = [
        # Docker reload variants (first check if running in docker-compose environment)
        ["docker", "exec", "waf-openresty", "openresty", "-s", "reload"],
        ["docker", "exec", "waf-openresty", "nginx", "-s", "reload"],
        # sudo variants (for non-root service user via sudoers grant)
        ["sudo", "/usr/local/openresty/bin/openresty", "-s", "reload"],
        ["sudo", "/usr/local/openresty/nginx/sbin/nginx", "-s", "reload"],
        # Direct variants (when running as root)
        ["/usr/local/openresty/bin/openresty", "-s", "reload"],
        ["/usr/local/openresty/nginx/sbin/nginx", "-s", "reload"],
        ["openresty", "-s", "reload"],
        ["nginx", "-s", "reload"],
    ]
    for cmd in candidates:
        try:
            result = subprocess.run(
                cmd, capture_output=True, text=True, timeout=10  # nosec B603
            )
            if result.returncode == 0:
                logger.info(f"NGINX/OpenResty reloaded successfully via: {' '.join(cmd)}")
                return True
            else:
                logger.warning(
                    f"Reload via '{' '.join(cmd)}' failed (rc={result.returncode}): "
                    f"{result.stderr.strip()}"
                )
        except FileNotFoundError:
            logger.debug(f"Command not found: {cmd[0]}, trying next...")
            continue
        except subprocess.TimeoutExpired:
            logger.error(f"Reload command timed out: {' '.join(cmd)}")
            continue
        except Exception as e:
            logger.error(f"Error reloading via '{' '.join(cmd)}': {e}")
            continue
    logger.error("All NGINX/OpenResty reload attempts exhausted. Check sudoers and binary paths.")
    return False


def get_redis_client():
    """
    Get Redis client using centralized configuration.
    This function now delegates to app.utils.redis_client.get_redis_client()
    for consistent password handling across the codebase.
    """
    from app.utils.redis_client import get_redis_client as get_centralized_client
    return get_centralized_client()


def apply_hardening_settings(settings: dict) -> bool:
    """
    Generates NGINX hardening configuration (server_tokens) and stores whitelisted/blacklisted
    IPs dynamically in Redis to enable zero-reload IP blocking.
    """
    try:
        server_cloaking = settings.get("server_cloaking", True)
        ip_blacklist = settings.get("ip_blacklist", [])
        ip_whitelist = settings.get("ip_whitelist", [])

        # 1. Update dynamic IP Whitelist/Blacklist in Redis
        r = get_redis_client()
        
        # Flush previous keys
        r.delete("waf:whitelist", "waf:whitelist:cidrs", "waf:blacklist", "waf:blacklist:cidrs")
        
        # Add whitelist
        for ip in ip_whitelist:
            ip = ip.strip()
            if ip:
                if not _validate_ip_or_cidr(ip):
                    logger.warning(f"Skipping invalid IP/CIDR in whitelist: '{ip}'")
                    continue
                if "/" in ip:
                    r.sadd("waf:whitelist:cidrs", ip)
                else:
                    r.sadd("waf:whitelist", ip)

        # Add blacklist
        for ip in ip_blacklist:
            ip = ip.strip()
            if ip:
                if not _validate_ip_or_cidr(ip):
                    logger.warning(f"Skipping invalid IP/CIDR in blacklist: '{ip}'")
                    continue
                if "/" in ip:
                    r.sadd("waf:blacklist:cidrs", ip)
                else:
                    r.sadd("waf:blacklist", ip)

        logger.info("Successfully updated dynamic WAF IP whitelist/blacklist in Redis.")

        # 2. Write server_tokens configuration to files
        config_lines = [
            "# Auto-generated by CyberSentinel WAF GUI",
            "# Do not edit manually",
            "",
        ]

        if server_cloaking:
            config_lines.append("server_tokens off;")
        else:
            config_lines.append("server_tokens on;")

        config_lines.append("")
        config_content = "\n".join(config_lines) + "\n"

        # Check if config content changed before writing and reloading to achieve zero-reload IP blocking
        existing_content = ""
        if os.path.exists(HARDENING_CONF_PATH):
            with open(HARDENING_CONF_PATH, "r", encoding="utf-8") as f:
                existing_content = f.read()

        if existing_content == config_content:
            logger.info("NGINX hardening config (server_tokens) is unchanged. Skipping NGINX reload.")
            return True

        with open(HARDENING_CONF_PATH, "w", encoding="utf-8") as f:
            f.write(config_content)

        logger.info(
            f"Successfully generated NGINX hardening config at {HARDENING_CONF_PATH}"
        )
        return reload_nginx()
    except Exception as e:
        logger.error(f"Failed to apply hardening settings: {e}")
        return False


def sync_protected_apps_to_nginx() -> bool:
    """
    Generates NGINX virtual host configurations for all active protected applications
    and reloads NGINX.
    """
    from app.services.db_service import get_all_protected_apps
    
    try:
        apps = get_all_protected_apps()
        active_apps = [app for app in apps if app.get("is_active", 1) == 1]
        
        # 1. Generate dynamic rate limit zones file in /etc/nginx/conf.d/
        rate_limit_lines = [
            "# Auto-generated by CyberSentinel WAF GUI",
            "# Per-application rate limit zones definition",
            ""
        ]
        
        for app in active_apps:
            app_id = app.get("id")
            rate_rps = app.get("rate_limit_rps", 50)
            rate_limit_lines.append(
                f"limit_req_zone $binary_remote_addr zone=zone_app_{app_id}:10m rate={rate_rps}r/s;"
            )
            
        rate_limits_content = "\n".join(rate_limit_lines) + "\n"
        rate_limits_conf_path = "/etc/nginx/conf.d/waf_app_rate_limits.conf"
        
        with open(rate_limits_conf_path, "w", encoding="utf-8") as f:
            f.write(rate_limits_content)
            
        logger.info(f"Successfully generated dynamic rate limits config at {rate_limits_conf_path}")

        # 2. Generate virtual host server blocks with health checked upstreams
        if not active_apps:
            logger.warning("No active protected applications found in database. NGINX config not updated.")
            return False
            
        config_lines = [
            "# =============================================================================",
            "# Dynamic WAF Protected Applications — Virtual Host Configuration",
            "# Auto-generated by CyberSentinel WAF GUI",
            "# Do not edit manually",
            "# =============================================================================",
            "",
            "# Port 80 HTTP -> HTTPS redirector",
            "server {",
            "    listen 80 default_server;",
            "    listen [::]:80 default_server;",
            "    server_name _;",
            "    access_log /var/log/nginx/http_redirect.log combined;",
            "    return 301 https://$host$request_uri;",
            "}",
            ""
        ]

        has_wildcard_default = any(app.get("domain") == "_" for app in active_apps)
        
        for idx, app in enumerate(active_apps):
            app_id = app.get("id")
            name = app.get("name", f"App {app_id}")
            domain = app.get("domain", "_").strip().lower()
            upstream_host = app.get("upstream_host", "host.docker.internal").strip()
            upstream_port = app.get("upstream_port", 7000)
            protocol = app.get("protocol", "http").strip().lower()
            burst = app.get("burst_tolerance", 100)
            
            # Decide if default_server is applied
            is_default = False
            if domain == "_":
                is_default = True
            elif not has_wildcard_default and idx == 0:
                is_default = True
                
            listen_suffix = " default_server" if is_default else ""
            
            config_lines.extend([
                f"# --- Upstream App {app_id}: {name} ({domain}) ---",
                f"upstream upstream_app_{app_id} {{",
                f"    server {upstream_host}:{upstream_port} max_fails=3 fail_timeout=10s;",
                "}",
                "",
                f"# --- App {app_id}: {name} ({domain}) ---",
                "server {",
                f"    listen 443 ssl{listen_suffix};",
                f"    listen [::]:443 ssl{listen_suffix};",
                "    http2 on;",
                f"    server_name {domain};",
                "",
                "    ssl_certificate     /etc/nginx/ssl/cybersentinel.crt;",
                "    ssl_certificate_key /etc/nginx/ssl/cybersentinel.key;",
                "",
                "    resolver 127.0.0.11 valid=30s ipv6=off;",
                "",
                "    location @json_forbidden {",
                "        default_type application/json;",
                "        add_header Content-Type 'application/json; charset=utf-8' always;",
                "        return 403 '{\"error\": \"🚨 WAF caught you! This attack has been blocked 🚫 and logged 📋. CyberSentinel is watching 👀\", \"code\": 403}';",
                "    }",
                "",
                "    location / {",
                f"        limit_req zone=zone_app_{app_id} burst={burst};",
                f"        proxy_pass {protocol}://upstream_app_{app_id};",
                "        proxy_http_version 1.1;",
                "        proxy_set_header Upgrade $http_upgrade;",
                "        proxy_set_header Connection 'upgrade';",
                "        proxy_set_header Host $host;",
                "        proxy_set_header X-Real-IP $remote_addr;",
                "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
                "        proxy_set_header X-Forwarded-Proto $scheme;",
                "        proxy_next_upstream error timeout http_502 http_503;",
                "        proxy_next_upstream_tries 3;",
                "        proxy_next_upstream_timeout 10s;",
                "    }",
                "",
                "    location /api {",
                "        error_page 403 = @json_forbidden;",
                f"        limit_req zone=zone_app_{app_id} burst={max(5, burst // 3)} nodelay;",
                "",
                f"        proxy_pass {protocol}://upstream_app_{app_id};",
                "        proxy_http_version 1.1;",
                "        proxy_set_header Upgrade $http_upgrade;",
                "        proxy_set_header Connection 'upgrade';",
                "        proxy_set_header Host $host;",
                "        proxy_set_header X-Real-IP $remote_addr;",
                "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
                "        proxy_set_header X-Forwarded-Proto $scheme;",
                "        proxy_next_upstream error timeout http_502 http_503;",
                "        proxy_next_upstream_tries 3;",
                "        proxy_next_upstream_timeout 10s;",
                "    }",
                "}",
                ""
            ])
            
        config_content = "\n".join(config_lines) + "\n"
        apps_conf_path = "/etc/nginx/sites-enabled/mssp"
        
        with open(apps_conf_path, "w", encoding="utf-8") as f:
            f.write(config_content)
            
        logger.info(f"Successfully generated dynamic WAF apps config at {apps_conf_path}")
        return reload_nginx()
    except Exception as e:
        logger.error(f"Failed to sync protected apps to NGINX: {e}")
        return False
