import os
import re
import json
import subprocess
import tempfile
import ipaddress
import logging

logger = logging.getLogger(__name__)

DDOS_CONF_PATH = "/etc/nginx/conf.d/waf_ddos.conf"

# The location-level half of DDoS/bot rate limiting.
#
# nginx does not merge limit_req across configuration levels — a location
# containing ANY limit_req directive replaces every inherited one instead of
# adding to it (same for limit_conn). Every proxying location in this product
# declares its own per-app or per-API zone, so the http-level limit_req lines
# in waf_ddos.conf were silently overridden everywhere and the DDoS & Bot
# Shield page configured zones that never evaluated a single request
# (audit finding P1-04).
#
# This file carries those same directives in a form each location can pull in
# with `include`, so they apply ALONGSIDE the location's own zone rather than
# being replaced by it. Deliberately NOT named *.conf: nginx.conf does
# `include /etc/nginx/conf.d/*.conf` at http level, and these directives are
# only valid inside a location.
#
# Always written, even when DDoS protection is disabled (as a comment-only
# file), because the generated vhosts include it unconditionally and a missing
# include file is a hard nginx startup failure.
DDOS_LIMITS_INCLUDE_PATH = "/etc/nginx/conf.d/waf_ddos_limits.inc"

HARDENING_CONF_PATH = "/etc/nginx/conf.d/waf_hardening.conf"
# NOT Included globally from modsec/main.conf (that applies to every server
# block, including the WAF GUI's own dashboard on port 3020 — confirmed via
# nginx.conf's `modsecurity_rules_file /etc/nginx/modsec/main.conf;` at the
# http{} level). Instead, sync_protected_apps_to_nginx() references this
# file with a per-server-block `modsecurity_rules_file` directive inside
# each PROTECTED APP's own generated server{} block only — the same scoping
# pattern already used by the dashboard's own vhost
# (configs/nginx/sites-available/cybersentinel) for its CRS exclusions.
# This is what keeps a Positive Security policy from ever applying to the
# dashboard's own admin traffic, without needing any URI-prefix guessing.
POSITIVE_SECURITY_CONF_PATH = "/etc/nginx/modsec/positive-security.conf"

# Malware scanning (P1-10) — same global, per-server-block-included scoping
# as POSITIVE_SECURITY_CONF_PATH above (one shared file, referenced from
# every protected app's own server{} block, never the dashboard's own
# vhost). MALWARE_SCAN_SCRIPT_PATH is the @inspectFile target invoked by
# ModSecurity for every uploaded file part — its content (not just the
# .conf's) is regenerated by apply_malware_scanning_settings() below,
# since the fail-open/fail-closed branch on a ClamAV-unreachable scan is
# baked into the script text itself, not read from a separate config file
# at scan time.
MALWARE_SCAN_CONF_PATH = "/etc/nginx/modsec/malware-scan.conf"
MALWARE_SCAN_SCRIPT_PATH = "/etc/nginx/modsec/malware-scan.sh"

# Per-protected-app require-auth (Phase 3) rule files. One file per app
# (not a shared global one) since each app can configure its own header/
# cookie name — same modsecurity_rules_file-per-server-block scoping as
# POSITIVE_SECURITY_CONF_PATH above, just app-specific instead of shared.
APP_AUTH_CONF_DIR = "/etc/nginx/modsec/app-auth"

# Admin-configurable "WAF blocked you" page (Settings > Custom Response).
# Referenced by an `internal` location added to every protected app's own
# generated server{} block (see sync_protected_apps_to_nginx()) — never the
# dashboard's own vhost, same per-server-block scoping as
# POSITIVE_SECURITY_CONF_PATH/APP_AUTH_CONF_DIR above.
CUSTOM_RESPONSE_PAGE_PATH = "/etc/nginx/custom_pages/waf_block.html"

# Basic per-app response caching (roadmap item — the audit's "real first
# step toward a CDN" call, not a CDN itself). One cache zone + disk dir per
# app, generated the same way rate-limit zones are (see
# APP_CACHE_ZONES_CONF_PATH below), rather than one shared zone across all
# apps — keeps each app's cache independently sized/evictable and avoids
# needing a cross-app cache key scheme.
#
# Deliberately under /etc/nginx (the same host directory both `backend` and
# `openresty` already bind-mount — see docker-compose.yml), NOT the more
# conventional /var/cache/nginx: that path exists only inside the openresty
# container's own filesystem, which this code (running in the `backend`
# container) has no way to create or write to. Putting it here means the
# ordinary os.makedirs() below is enough — no cross-container exec needed,
# same trick already used for SSL certs/sites-enabled/modsec confs.
APP_CACHE_BASE_DIR = "/etc/nginx/proxy_cache"
APP_CACHE_ZONES_CONF_PATH = "/etc/nginx/conf.d/waf_app_cache_zones.conf"

# mTLS for API auth (roadmap item) — one CA cert file per app, same
# /etc/nginx-bind-mount trick as APP_CACHE_BASE_DIR above (both backend
# and openresty mount this same host directory, so a plain file write from
# here is immediately visible to openresty at reload time).
APP_MTLS_CA_DIR = "/etc/nginx/ssl/mtls"

REDIS_SECRET_FILE = "/etc/cybersentinel/redis.secret"  # nosec B105


def _get_redis_password() -> str:
    """
    Reads the Redis authentication password from a protected secret file.
    Falls back to empty string (no auth) if the file does not exist.
    """
    try:
        with open(REDIS_SECRET_FILE, "r") as f:
            return f.read().strip()
    except FileNotFoundError:
        logger.warning(
            f"Redis secret file not found at {REDIS_SECRET_FILE}. "
            "Connecting without authentication."
        )
        return ""
    except Exception as e:
        logger.error(f"Failed to read Redis secret file: {e}")
        return ""


def _sanitize_nginx_pattern(value: str) -> str:
    """
    Strips characters that would break NGINX map block structure or allow
    arbitrary directive injection via user-supplied rate limiting patterns.
    Removes: { } ; newlines and carriage returns.
    """
    return re.sub(r'[{};\'"\n\r]', '', value)


def _validate_ip_or_cidr(ip: str) -> bool:
    """
    Validates that a string is a valid IPv4/IPv6 address or CIDR network.
    Returns True if valid, False otherwise.
    """
    try:
        ipaddress.ip_network(ip.strip(), strict=False)
        return True
    except ValueError:
        return False


# JA4's fixed a_b_c shape (see ml-waf/ja4_core.lua's part_a/part_b/part_c):
# a 10-char part A (protocol+version+sni+cipher_count+ext_count+alpn),
# then two 12-char lowercase-hex SHA-256-truncated parts. This is a shape
# check only, not proof the fingerprint corresponds to any real client an
# admin has actually observed — they may be pasting one in from an
# external threat-intel source rather than one this WAF captured itself.
_JA4_RE = re.compile(r"^[a-z0-9]{10}_[0-9a-f]{12}_[0-9a-f]{12}$")


def _validate_ja4(fingerprint: str) -> bool:
    """Validates that a string matches JA4's fixed format. Returns True if
    valid, False otherwise."""
    return bool(_JA4_RE.match(fingerprint.strip().lower()))


def _atomic_write(path: str, content: str) -> None:
    """
    Writes `content` to `path` via temp file + os.replace() so a crash or
    power loss mid-write can never leave a truncated/corrupt config file on
    disk — same pattern as rule_manager's override-file writer.
    """
    directory = os.path.dirname(path)
    os.makedirs(directory, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(dir=directory, prefix=".nginxcfg-", suffix=".tmp")
    try:
        # mkstemp() creates the file at mode 0600 (owner read/write only) and
        # os.replace() carries that mode over — nginx configs need to stay
        # world-readable like the files they replace, or OpenResty running as
        # a different uid (or any non-root debugging/backup tooling on the
        # host) silently loses the ability to read its own config.
        os.chmod(tmp_path, 0o644)
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(content)
        os.replace(tmp_path, path)
    except Exception:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)
        raise


def write_and_apply_configs(file_contents: dict) -> tuple[bool, str]:
    """
    Writes one or more generated NGINX config files, validates the *full*
    config syntax with test_nginx_config(), and only reloads if it's valid —
    restoring every file to its prior state (or deleting it, if it didn't
    exist before) on failure.

    This matters because `nginx -s reload`'s exit code only reflects whether
    the running master process could be *signaled*, not whether it accepted
    the new config: nginx re-validates asynchronously inside the master
    after the reload command has already returned, so a caller that trusts
    reload_nginx()'s return value alone can silently believe a bad config
    was applied when nginx actually rejected it and kept running the old
    one. Callers should surface the returned message to the admin instead
    of a generic "failed" — it's the actual nginx config test output.
    """
    backups = {}
    try:
        for path, content in file_contents.items():
            if os.path.exists(path):
                with open(path, "r", encoding="utf-8") as f:
                    backups[path] = f.read()
            else:
                backups[path] = None
            _atomic_write(path, content)
    except Exception as e:
        logger.error(f"Failed to write NGINX config file(s): {e}")
        return False, f"Failed to write configuration file(s): {e}"

    valid, err_msg = test_nginx_config()
    if not valid:
        for path, old_content in backups.items():
            try:
                if old_content is None:
                    if os.path.exists(path):
                        os.remove(path)
                else:
                    _atomic_write(path, old_content)
            except Exception as restore_err:
                logger.error(f"Failed to restore {path} after invalid config: {restore_err}")
        logger.error(f"NGINX config validation failed, changes rolled back: {err_msg}")
        return False, f"NGINX configuration validation failed (changes rolled back): {err_msg}"

    if not reload_nginx():
        return False, "NGINX configuration is valid but the reload command failed. Check system permissions and sudoers/docker exec access."

    return True, ""


def apply_ddos_settings(settings: dict) -> tuple[bool, str]:
    """
    Generates NGINX rate-limiting configuration based on the provided settings
    and reloads NGINX to apply them.
    """
    try:
        rate_limit_rps = settings.get("rate_limit_rps", 50)
        burst_tolerance = settings.get("burst_tolerance", 100)
        trusted_ips = settings.get("trusted_ips", [])
        bot_action = settings.get("bot_mitigation_action", "Silent Drop")
        advanced_rules = settings.get("advanced_rules", [])

        # General rate-limit zones (waf_ddos_req/waf_ddos_conn below, and
        # every zone that inherits limit_req_status/limit_conn_status from
        # http level because it doesn't declare its own — login_limit,
        # api_limit, ws_conn_limit on the console, every generated app's
        # zone_app_<id>) ALWAYS return 429. This used to be `status_code =
        # 444 if bot_action == "Silent Drop" else 429`, applied globally —
        # but limit_req_status/limit_conn_status are single, shared-per-
        # scope directives, not per-zone, so the bot-mitigation dropdown
        # (meant only to control how confirmed-bad-bot-UA traffic gets
        # handled) was silently overriding the status for EVERY unrelated
        # rate limit in the product too: a legitimate client tripping the
        # login rate limiter, or any customer app's own API rate limit,
        # got a silently-closed connection with no Retry-After the moment
        # an admin picked "Silent Drop" for bots (audit finding P2-07).
        GENERAL_RATE_LIMIT_STATUS = 429

        # Bad-bot-UA traffic (the map below) is no longer rate-limited via
        # a native nginx zone at all — that's what made it share a status
        # with the general zones above in the first place. It's now
        # enforced in Lua instead (ml_check.lua's check_bad_bot_rate_limit,
        # mirroring check_adaptive_throttle's Redis INCR+EXPIRE pattern),
        # which can exit with whichever status THIS setting says without
        # touching any other zone. 0 means "don't apply this check at
        # all" — JS Challenge mode already has its own mechanism below.
        if bot_action == "Silent Drop":
            bot_mitigation_status_code = 444
        elif bot_action == "Block":
            bot_mitigation_status_code = 429
        else:
            bot_mitigation_status_code = 0

        # JS Challenge: instead of an outright reject, bad-UA-matching traffic
        # gets an interstitial (ml-waf/bot_challenge.lua) that a real browser's
        # JS clears itself; a scripted client never does. That flow needs at
        # least two requests from the same client in quick succession (the
        # initial hit + the JS-triggered reload), so
        # check_bad_bot_rate_limit() (1r/m, effectively "block after the
        # first request") must NOT also apply, or the reload itself gets
        # rejected before Lua's bot_challenge.check() ever sees it —
        # bot_mitigation_status_code is 0 for this mode for exactly that
        # reason (see where it's set above).
        bot_challenge_enabled = bot_action == "JS Challenge"

        config_lines = [
            "# Auto-generated by CyberSentinel WAF GUI",
            "# Do not edit manually",
            "",
        ]

        # Mirror of every limit_req this function emits at http level, in a
        # form each proxying location includes so the zones actually evaluate.
        # See DDOS_LIMITS_INCLUDE_PATH for why this duplication is required.
        location_limit_lines = [
            "# Auto-generated by CyberSentinel WAF GUI — DDoS/bot rate limits",
            "# Do not edit manually. Included from inside each proxying location,",
            "# so these zones apply IN ADDITION to that location's own limit_req,",
            "# which would otherwise replace them outright (nginx does not merge",
            "# limit_req across levels). See nginx_manager.DDOS_LIMITS_INCLUDE_PATH.",
            "",
        ]

        # Define GeoIP2 databases if they exist on disk AND the geoip2 nginx module is loaded.
        # GEOIP_DATA_DIR env var allows portable deployment on client servers.
        # Falls back to the demo-server absolute path when env var is not set.
        # GEOIP2_MODULE_ENABLED must be set to "true" once OpenResty is rebuilt with the module.
        geoip2_module_enabled = os.environ.get("GEOIP2_MODULE_ENABLED", "false").lower() == "true"

        _geoip_dir = os.environ.get(
            "GEOIP_DATA_DIR",
            os.path.abspath(
                os.path.join(os.path.dirname(os.path.dirname(__file__)), "data")
            )
        )
        COUNTRY_DB = os.path.join(_geoip_dir, "GeoLite2-Country.mmdb")
        ASN_DB = os.path.join(_geoip_dir, "GeoLite2-ASN.mmdb")

        has_country_db = os.path.exists(COUNTRY_DB)
        has_asn_db = os.path.exists(ASN_DB)

        if geoip2_module_enabled and has_country_db:
            config_lines.append(f"geoip2 {COUNTRY_DB} {{")
            config_lines.append(
                "    $geoip2_data_country_code source=$remote_addr country iso_code;"
            )
            config_lines.append("}")
            config_lines.append("")
        elif has_country_db:
            config_lines.append(
                "# geoip2 module not loaded — set GEOIP2_MODULE_ENABLED=true after rebuilding OpenResty"
            )
            config_lines.append("")

        if geoip2_module_enabled and has_asn_db:
            config_lines.append(f"geoip2 {ASN_DB} {{")
            config_lines.append(
                "    $geoip2_data_asn source=$remote_addr autonomous_system_number;"
            )
            config_lines.append(
                "    $geoip2_data_org source=$remote_addr autonomous_system_organization;"
            )
            config_lines.append("}")
            config_lines.append("")

        # --- Bot Mitigation ---
        config_lines.append("# --- Bot Mitigation ---")
        config_lines.append("map $http_user_agent $is_bad_bot {")
        config_lines.append("    default 0;")
        # Malicious crawlers & scrapers
        config_lines.append('    "~*semrush" 1;')
        config_lines.append('    "~*ahrefs" 1;')
        config_lines.append('    "~*mj12bot" 1;')
        config_lines.append('    "~*dotbot" 1;')
        config_lines.append('    "~*rogerbot" 1;')
        config_lines.append('    "~*megaindex" 1;')
        config_lines.append('    "~*zoominfobot" 1;')
        config_lines.append('    "~*yandexbot" 1;')
        config_lines.append('    "~*baiduspider" 1;')
        config_lines.append('    "~*screaming frog" 1;')
        # Vulnerability scanners & tools
        config_lines.append('    "~*sqlmap" 1;')
        config_lines.append('    "~*nmap" 1;')
        config_lines.append('    "~*nikto" 1;')
        config_lines.append('    "~*dirbuster" 1;')
        config_lines.append('    "~*censys" 1;')
        config_lines.append('    "~*shodan" 1;')
        config_lines.append('    "~*netsparker" 1;')
        config_lines.append('    "~*acunetix" 1;')
        # Common HTTP client libraries used for botting
        config_lines.append('    "~*python-requests" 1;')
        config_lines.append('    "~*pycurl" 1;')
        config_lines.append('    "~*urllib" 1;')
        config_lines.append('    "~*wget" 1;')
        # Empty user-agent or standard hyphen
        config_lines.append('    "-" 1;')
        config_lines.append('    "" 1;')
        config_lines.append("}")
        config_lines.append("")
        # Bad-bot-UA traffic used to get its own limit_req_zone here (keyed
        # by client IP, 1r/m) — moved to ml_check.lua's
        # check_bad_bot_rate_limit() instead (see GENERAL_RATE_LIMIT_STATUS
        # above for why: it shared a status code with every other rate
        # limit in the product). $is_bad_bot above still drives it, just
        # read directly as an nginx variable from Lua rather than through a
        # dedicated zone.

        # We always define the $limit_key variable.
        # If trusted_ips exist, it is dynamic. If not, it is equivalent to $binary_remote_addr.
        if trusted_ips:
            config_lines.append("geo $limit {")
            config_lines.append("    default 1;")
            for ip in trusted_ips:
                ip = ip.strip()
                if ip:
                    if not _validate_ip_or_cidr(ip):
                        logger.warning(f"Skipping invalid IP/CIDR in trusted list: '{ip}'")
                        continue
                    config_lines.append(f"    {ip} 0;")
            config_lines.append("}")
            config_lines.append("")
            config_lines.append("map $limit $limit_key {")
            config_lines.append('    0 "";')
            config_lines.append("    1 $binary_remote_addr;")
            config_lines.append("}")
        else:
            config_lines.append("map $host $limit_key {")
            config_lines.append("    default $binary_remote_addr;")
            config_lines.append("}")

        config_lines.append("")
        zone_key = "$limit_key"

        config_lines.append(
            f"limit_req_zone {zone_key} zone=waf_ddos_req:10m rate={rate_limit_rps}r/s;"
        )
        config_lines.append(f"limit_req_status {GENERAL_RATE_LIMIT_STATUS};")
        config_lines.append("")
        # These two http-level limit_req directives are a FALLBACK ONLY, for
        # locations that declare no limit_req of their own.
        #
        # nginx does not merge limit_req across configuration levels: a
        # location containing any limit_req directive REPLACES every
        # inherited one rather than adding to it. Every proxying location in
        # this product declares its own (zone_app_<id> in the generated app
        # vhosts, api_limit/login_limit in the console vhost), so these
        # http-level lines applied to essentially no real traffic at all.
        #
        # Confirmed live before the fix: four consecutive requests with
        # User-Agent "Wget/1.21" — which the map above classifies as a bad
        # bot, against a zone rated 1r/m with burst=1 — all returned 200.
        # The entire DDoS & Bot Shield page was configuring zones that never
        # evaluated a request while presenting as active (audit finding
        # P1-04). The per-location half of the fix is DDOS_LIMITS_INCLUDE_PATH
        # below, which every generated location now includes.
        config_lines.append(
            f"limit_req zone=waf_ddos_req burst={burst_tolerance} nodelay;"
        )
        location_limit_lines.append(
            f"limit_req zone=waf_ddos_req burst={burst_tolerance} nodelay;"
        )
        config_lines.append("")

        # Config-time boolean exposed as a runtime nginx variable so
        # bot_challenge.lua knows whether this mode is active — "map $host"
        # with only a default entry ignores $host entirely and just always
        # yields the same baked-in value (a standard nginx trick for
        # injecting a Python-decided constant into the request-variable
        # namespace Lua can read).
        config_lines.append(f"map $host $waf_bot_challenge_enabled {{")
        config_lines.append(f"    default {1 if bot_challenge_enabled else 0};")
        config_lines.append("}")
        config_lines.append("")

        # Same trick, carrying the status ml_check.lua's
        # check_bad_bot_rate_limit() should exit with for a rate-limited
        # bad-bot request — 444 (Silent Drop), 429 (Block), or 0 (JS
        # Challenge / any other mode — don't apply this check at all).
        # This is what lets that check use a different status than every
        # other rate limit in the product without them sharing a
        # limit_req_status scope (see GENERAL_RATE_LIMIT_STATUS above).
        config_lines.append(f"map $host $waf_bot_mitigation_status {{")
        config_lines.append(f"    default {bot_mitigation_status_code};")
        config_lines.append("}")
        config_lines.append("")

        # Independent toggle for the same challenge mechanism, triggered by
        # ml_server.py's X-WAF-Risk-Challenge response header (threat_score's
        # "log" band) instead of the bad-bot UA signal above. No interaction
        # with the bad-bot rate limit above — this path never touches it.
        risk_challenge_enabled = settings.get("risk_challenge_enabled", False)
        config_lines.append(f"map $host $waf_risk_challenge_enabled {{")
        config_lines.append(f"    default {1 if risk_challenge_enabled else 0};")
        config_lines.append("}")
        config_lines.append("")

        # Independent toggle: a tighter, Lua/Redis-enforced rate check for
        # IPs whose reputation (rep:{ip}, written by ml_server.py on
        # confirmed blocks) has crossed a threshold — layered on top of,
        # never replacing, the native limit_req zones below, which must
        # keep working even when Redis/ML are degraded. See ml_check.lua's
        # check_adaptive_throttle().
        adaptive_throttle_enabled = settings.get("adaptive_throttle_enabled", False)
        config_lines.append(f"map $host $waf_adaptive_throttle_enabled {{")
        config_lines.append(f"    default {1 if adaptive_throttle_enabled else 0};")
        config_lines.append("}")
        config_lines.append("")

        # API sequential-enumeration detection toggle — see enum_detect.lua.
        # Same $host-keyed map shape as adaptive_throttle_enabled just
        # above (it's a plain settings field on this same ddos-bot dict,
        # unlike good_bot_enabled below which lives in its own namespace).
        api_enum_protection_enabled = settings.get("api_enum_protection_enabled", False)
        config_lines.append(f"map $host $waf_api_enum_enabled {{")
        config_lines.append(f"    default {1 if api_enum_protection_enabled else 0};")
        config_lines.append("}")
        config_lines.append("")

        # Verified-good-bot allowlist toggle (Settings > Hardening ->
        # good_bot_service.py) — its own settings namespace, not part of
        # the ddos-bot `settings` dict passed into this function, so it's
        # read directly rather than threaded through as a parameter.
        # Read here (not in ml_check.lua) so the check is a zero-cost `if`
        # on an nginx variable when disabled, same pattern as every other
        # toggle in this block, rather than a Redis round-trip per request
        # to find out the feature is off.
        from app.services.settings_manager import settings_manager as _settings_manager
        good_bot_enabled = _settings_manager.get_good_bots().get("enabled", False)
        config_lines.append(f"map $host $waf_good_bot_enabled {{")
        config_lines.append(f"    default {1 if good_bot_enabled else 0};")
        config_lines.append("}")
        config_lines.append("")

        # Connection limiting
        config_lines.append(f"limit_conn_zone {zone_key} zone=waf_ddos_conn:10m;")
        config_lines.append(f"limit_conn_status {GENERAL_RATE_LIMIT_STATUS};")
        config_lines.append(
            "limit_conn waf_ddos_conn 100;"
        )  # Hardcoded max 100 connections per IP for now
        config_lines.append("")

        # --- Advanced Rate Limiting Rules ---
        if advanced_rules:
            config_lines.append("# --- Advanced Rate Limiting Rules ---")
            for rule in advanced_rules:
                if not rule.get("enabled", True):
                    continue
                rule_id = rule.get("id")
                rule_name = rule.get("name", f"Rule {rule_id}")
                param_type = rule.get("parameter_type", "URI")
                param_value = rule.get("parameter_value", "")
                rule_rps = rule.get("rate_limit_rps", 10)
                rule_burst = rule.get("burst_tolerance", 20)

                # Determine NGINX variable to inspect and whether to rate-limit by the value itself
                nginx_var = "$request_uri"
                limit_by_value = False
                if param_type == "URI":
                    nginx_var = "$request_uri"
                elif param_type == "Host+URI":
                    # Plain "URI" rules match $request_uri alone, which is
                    # shared across every vhost this gateway proxies — a rule
                    # for "/login" would rate-limit that path on EVERY
                    # protected app, not just the one it was meant for.
                    # Host+URI scopes the match to one specific app's domain
                    # (used by the per-app login/brute-force protection
                    # feature in ProtectedApps.jsx).
                    nginx_var = "$host$request_uri"
                elif param_type == "Method":
                    nginx_var = "$request_method"
                elif param_type == "Referrer":
                    nginx_var = "$http_referer"
                elif param_type == "Content-Type":
                    nginx_var = "$http_content_type"
                elif param_type == "IP":
                    nginx_var = "$remote_addr"
                elif param_type == "Session":
                    # cookie_name comes straight from the admin-supplied rule
                    # payload with no character restriction — embedded raw
                    # into an nginx variable-name token, an unsanitized value
                    # containing e.g. a newline or `{` could break out of the
                    # generated map block into arbitrary config injection.
                    cookie_name = param_value.strip() or "session"
                    safe_cookie_name = re.sub(r"[^A-Za-z0-9_-]", "", cookie_name).lower().replace("-", "_")
                    if not safe_cookie_name:
                        logger.warning(f"Skipping rule '{rule_name}': cookie name is empty after sanitization.")
                        continue
                    nginx_var = f"$cookie_{safe_cookie_name}"
                    limit_by_value = True
                elif param_type == "Country":
                    if not geoip2_module_enabled or not has_country_db:
                        logger.warning(
                            f"Skipping Country rate limiting rule '{rule_name}' — geoip2 module not enabled or Country GeoIP DB missing."
                        )
                        continue
                    nginx_var = "$geoip2_data_country_code"
                elif param_type == "ISP/ASN":
                    if not geoip2_module_enabled or not has_asn_db:
                        logger.warning(
                            f"Skipping ISP/ASN rate limiting rule '{rule_name}' — geoip2 module not enabled or ASN GeoIP DB missing."
                        )
                        continue
                    # Match ASN (if numeric) or Org name
                    if param_value.strip().isdigit():
                        nginx_var = "$geoip2_data_asn"
                    else:
                        nginx_var = "$geoip2_data_org"
                elif param_type == "Header":
                    # Custom header parsing (e.g. "X-API-Key: value" or just "X-API-Key")
                    # Same raw-embedding risk as the Session/cookie case above —
                    # header_name is sanitized to a safe variable-name charset
                    # before being spliced into the generated $http_<name> token.
                    if ":" in param_value:
                        parts = param_value.split(":", 1)
                        header_name = parts[0].strip()
                        param_value = parts[1].strip()
                    else:
                        header_name = param_value.strip()
                        limit_by_value = True

                    safe_header_name = re.sub(r"[^A-Za-z0-9_-]", "", header_name).lower().replace("-", "_")
                    if not safe_header_name:
                        logger.warning(f"Skipping rule '{rule_name}': header name is empty after sanitization.")
                        continue
                    nginx_var = "$http_" + safe_header_name

                if limit_by_value:
                    config_lines.append(
                        f"# Rule: {rule_name} (Type: {param_type}, Limit by unique value of {nginx_var})"
                    )
                    config_lines.append(f"map {nginx_var} $limit_key_{rule_id} {{")
                    config_lines.append(f'    "~.+" {nginx_var};')
                    config_lines.append('    default "";')
                    config_lines.append("}")
                else:
                    # Sanitize pattern to prevent NGINX config injection
                    # Strip characters that can break NGINX map block structure
                    clean_value = _sanitize_nginx_pattern(param_value)
                    if not clean_value:
                        logger.warning(f"Skipping rule '{rule_name}': pattern is empty after sanitization.")
                        continue

                    config_lines.append(
                        f"# Rule: {rule_name} (Type: {param_type}, Match: {param_value})"
                    )
                    config_lines.append(f"map {nginx_var} $limit_key_{rule_id} {{")
                    # Map to $limit_key (so trusted IPs automatically bypass this check)
                    # If param_type is Country, IP, Host+URI, or numeric ISP/ASN, anchor
                    # matching with ^...$ to prevent substring matching
                    if param_type in ("Country", "IP", "Host+URI") or (param_type == "ISP/ASN" and param_value.strip().isdigit()):
                        config_lines.append(f'    "~*^{clean_value}$" {zone_key};')
                    else:
                        config_lines.append(f'    "~*{clean_value}" {zone_key};')
                    config_lines.append('    default "";')
                    config_lines.append("}")

                # Rate expressed per-second by default; per-minute is available
                # for rules needing finer granularity than an integer r/s
                # allows (e.g. login/brute-force protection — "5 attempts per
                # minute" has no clean r/s equivalent below 1r/s=60/min).
                rate_unit = rule.get("rate_limit_unit", "r/s")
                if rate_unit not in ("r/s", "r/m"):
                    rate_unit = "r/s"
                config_lines.append(
                    f"limit_req_zone $limit_key_{rule_id} zone=zone_{rule_id}:10m rate={rule_rps}{rate_unit};"
                )
                config_lines.append(
                    f"limit_req zone=zone_{rule_id} burst={rule_burst} nodelay;"
                )
                # Advanced rules were overridden at http level for exactly the
                # same reason as the two zones above — an admin's custom
                # per-country/per-ISP/per-header rule never fired either.
                location_limit_lines.append(
                    f"limit_req zone=zone_{rule_id} burst={rule_burst} nodelay;"
                )
                config_lines.append("")

        config_content = "\n".join(config_lines) + "\n"
        location_limits_content = "\n".join(location_limit_lines) + "\n"

        logger.info(f"Generated NGINX DDoS config for {DDOS_CONF_PATH}, validating before apply...")

        # Validate + apply + reload (rolls back BOTH files if the new config
        # is invalid — they must move together, since the .inc references
        # zones declared in waf_ddos.conf).
        return write_and_apply_configs({
            DDOS_CONF_PATH: config_content,
            DDOS_LIMITS_INCLUDE_PATH: location_limits_content,
        })

    except Exception as e:
        logger.error(f"Failed to apply DDoS settings: {e}")
        return False, str(e)


def reload_nginx() -> bool:
    """
    Reloads the NGINX/OpenResty service gracefully.
    Tries sudo-prefixed commands first (required when running as non-root service user).
    Falls back to direct execution if sudo is not available.
    Requires /etc/sudoers.d/cybersentinel-waf to grant NOPASSWD for these commands.
    """
    candidates = [
        # Docker reload variants (first check if running in docker-compose environment)
        ["docker", "exec", "waf-openresty", "openresty", "-c", "/etc/nginx/nginx.conf", "-s", "reload"],
        ["docker", "exec", "waf-openresty", "nginx", "-c", "/etc/nginx/nginx.conf", "-s", "reload"],
        # sudo variants (for non-root service user via sudoers grant)
        ["sudo", "/usr/local/openresty/bin/openresty", "-c", "/etc/nginx/nginx.conf", "-s", "reload"],
        ["sudo", "/usr/local/openresty/nginx/sbin/nginx", "-c", "/etc/nginx/nginx.conf", "-s", "reload"],
        # Direct variants (when running as root)
        ["/usr/local/openresty/bin/openresty", "-c", "/etc/nginx/nginx.conf", "-s", "reload"],
        ["/usr/local/openresty/nginx/sbin/nginx", "-c", "/etc/nginx/nginx.conf", "-s", "reload"],
        ["openresty", "-c", "/etc/nginx/nginx.conf", "-s", "reload"],
        ["nginx", "-c", "/etc/nginx/nginx.conf", "-s", "reload"],
    ]
    for cmd in candidates:
        try:
            result = subprocess.run(
                cmd, capture_output=True, text=True, timeout=10  # nosec B603
            )
            if result.returncode == 0:
                logger.info(f"NGINX/OpenResty reloaded successfully via: {' '.join(cmd)}")
                return True
            else:
                logger.warning(
                    f"Reload via '{' '.join(cmd)}' failed (rc={result.returncode}): "
                    f"{result.stderr.strip()}"
                )
        except FileNotFoundError:
            logger.debug(f"Command not found: {cmd[0]}, trying next...")
            continue
        except subprocess.TimeoutExpired:
            logger.error(f"Reload command timed out: {' '.join(cmd)}")
            continue
        except Exception as e:
            logger.error(f"Error reloading via '{' '.join(cmd)}': {e}")
            continue
    logger.error("All NGINX/OpenResty reload attempts exhausted. Check sudoers and binary paths.")
    return False


def get_redis_client():
    """
    Get Redis client using centralized configuration.
    This function now delegates to app.utils.redis_client.get_global_redis_client()
    for consistent password handling across the codebase.
    """
    from app.utils.redis_client import get_global_redis_client as get_centralized_client
    return get_centralized_client()


def apply_hardening_settings(settings: dict) -> tuple[bool, str]:
    """
    Generates NGINX hardening configuration (server_tokens) and stores whitelisted/blacklisted
    IPs dynamically in Redis to enable zero-reload IP blocking.
    """
    try:
        server_cloaking = settings.get("server_cloaking", True)
        ip_blacklist = settings.get("ip_blacklist", [])
        ip_whitelist = settings.get("ip_whitelist", [])
        ja4_blacklist = settings.get("ja4_blacklist", [])

        # 1. Update dynamic IP Whitelist/Blacklist in Redis
        r = get_redis_client()

        # Flush previous keys
        r.delete("waf:whitelist", "waf:whitelist:cidrs", "waf:blacklist", "waf:blacklist:cidrs", "waf:blacklist:ja4")
        
        # Add whitelist
        for ip in ip_whitelist:
            ip = ip.strip()
            if ip:
                if not _validate_ip_or_cidr(ip):
                    logger.warning(f"Skipping invalid IP/CIDR in whitelist: '{ip}'")
                    continue
                if "/" in ip:
                    r.sadd("waf:whitelist:cidrs", ip)
                else:
                    r.sadd("waf:whitelist", ip)

        # Add blacklist
        for ip in ip_blacklist:
            ip = ip.strip()
            if ip:
                if not _validate_ip_or_cidr(ip):
                    logger.warning(f"Skipping invalid IP/CIDR in blacklist: '{ip}'")
                    continue
                if "/" in ip:
                    r.sadd("waf:blacklist:cidrs", ip)
                else:
                    r.sadd("waf:blacklist", ip)

        # Add JA4 blacklist — exact-match only, a fingerprint has no CIDR
        # concept. Checked by ml_check.lua against the fingerprint ja4.lua
        # already cached per-connection during the TLS handshake; see that
        # file for why this is a single set rather than the IP list's
        # exact+CIDR+feed+auto tiers (no feed/auto source exists yet).
        for ja4 in ja4_blacklist:
            ja4 = ja4.strip().lower()
            if ja4:
                if not _validate_ja4(ja4):
                    logger.warning(f"Skipping invalid JA4 fingerprint in blacklist: '{ja4}'")
                    continue
                r.sadd("waf:blacklist:ja4", ja4)

        logger.info("Successfully updated dynamic WAF IP/JA4 whitelist/blacklist in Redis.")

        # 2. Write server_tokens configuration to files
        config_lines = [
            "# Auto-generated by CyberSentinel WAF GUI",
            "# Do not edit manually",
            "",
        ]

        if server_cloaking:
            config_lines.append("server_tokens off;")
        else:
            config_lines.append("server_tokens on;")

        config_lines.append("")
        config_content = "\n".join(config_lines) + "\n"

        # Check if config content changed before writing and reloading to achieve zero-reload IP blocking
        existing_content = ""
        if os.path.exists(HARDENING_CONF_PATH):
            with open(HARDENING_CONF_PATH, "r", encoding="utf-8") as f:
                existing_content = f.read()

        if existing_content == config_content:
            logger.info("NGINX hardening config (server_tokens) is unchanged. Skipping NGINX reload.")
            return True, ""

        logger.info(f"Generated NGINX hardening config for {HARDENING_CONF_PATH}, validating before apply...")
        return write_and_apply_configs({HARDENING_CONF_PATH: config_content})
    except Exception as e:
        logger.error(f"Failed to apply hardening settings: {e}")
        return False, str(e)


def apply_geo_block_settings(settings: dict) -> tuple[bool, str]:
    """
    Pushes the country allow/deny list into Redis for ml_check.lua to read —
    zero-reload, same pattern as apply_hardening_settings' IP whitelist/
    blacklist above. Requires GeoIP2 to actually be enabled (see
    apply_ddos_settings' geoip2 {} block generation) to have any effect;
    enforcement degrades to a no-op in ml_check.lua if
    $geoip2_data_country_code was never populated.
    """
    try:
        r = get_redis_client()
        enabled = settings.get("enabled", False)
        mode = settings.get("mode", "deny")
        countries = settings.get("countries", [])

        r.delete("waf:geo:countries")
        if enabled and mode in ("allow", "deny"):
            r.set("waf:geo:block_mode", mode)
            for code in countries:
                code = code.strip().upper()
                if code:
                    r.sadd("waf:geo:countries", code)
        else:
            r.set("waf:geo:block_mode", "disabled")

        logger.info(
            f"Successfully updated geo-block settings in Redis "
            f"(mode={mode if enabled else 'disabled'}, {len(countries)} countries)."
        )
        return True, ""
    except Exception as e:
        logger.error(f"Failed to apply geo-block settings: {e}")
        return False, str(e)


def apply_positive_security_settings(settings: dict) -> tuple[bool, str]:
    """
    Generates ModSecurity rules enforcing the Positive Security allowlist
    (allowed HTTP methods, allowed request Content-Types, restricted file
    extensions) and reloads to apply. Disabled by default — settings.get
    ("enabled") must be explicitly true, since these defaults (e.g.
    allowed_methods: GET/POST/HEAD only) would otherwise silently start
    rejecting any protected app that legitimately uses PUT/DELETE/PATCH the
    moment this feature shipped. When disabled, writes a comment-only file,
    which correctly removes any previously-active rules.

    Any of the three lists being empty just skips generating that specific
    check (not "block everything") — an accidentally-cleared field should
    degrade to "not enforced", not "deny all traffic".

    Scoping to protected-app traffic only (never the dashboard) is done by
    WHERE this file gets referenced (see POSITIVE_SECURITY_CONF_PATH's
    docstring above) — no skip rule needed here.
    """
    try:
        enabled = bool(settings.get("enabled", False))
        config_lines = [
            "# Auto-generated by CyberSentinel WAF GUI — Positive Security policy",
            "# Do not edit manually",
        ]

        if not enabled:
            config_lines.append("# Positive Security is currently disabled — no active rules.")
            config_content = "\n".join(config_lines) + "\n"
            logger.info("Positive Security is disabled — applying an empty policy.")
            return write_and_apply_configs({POSITIVE_SECURITY_CONF_PATH: config_content})

        allowed_methods = [m.strip().upper() for m in settings.get("allowed_methods", []) if m.strip()]
        allowed_content_types = [c.strip() for c in settings.get("allowed_content_types", []) if c.strip()]
        restricted_extensions = [e.strip().lower().lstrip(".") for e in settings.get("restricted_extensions", []) if e.strip()]

        config_lines.append("")

        if allowed_methods:
            method_pattern = "^(" + "|".join(re.escape(m) for m in allowed_methods) + ")$"
            config_lines.append(
                f'SecRule REQUEST_METHOD "!@rx {method_pattern}" '
                f'"id:5900002,phase:1,deny,status:405,log,'
                f"msg:'Method not allowed by Positive Security policy'\""
            )
            config_lines.append("")

        if allowed_content_types:
            ct_pattern = "^(" + "|".join(re.escape(c) for c in allowed_content_types) + ")"
            config_lines.append(
                'SecRule REQUEST_METHOD "@rx ^(POST|PUT|PATCH)$" '
                '"id:5900003,phase:1,chain,deny,status:415,log,'
                "msg:'Content-Type not allowed by Positive Security policy'\""
            )
            config_lines.append(
                f'    SecRule REQUEST_HEADERS:Content-Type "!@rx {ct_pattern}" ""'
            )
            config_lines.append("")

        if restricted_extensions:
            ext_pattern = r"\.(" + "|".join(re.escape(e) for e in restricted_extensions) + ")$"
            config_lines.append(
                f'SecRule REQUEST_FILENAME "@rx {ext_pattern}" '
                f'"id:5900004,phase:1,deny,status:403,log,t:lowercase,'
                f"msg:'Restricted file extension blocked by Positive Security policy'\""
            )
            config_lines.append("")
            # REQUEST_FILENAME above only ever matched the URL path (e.g.
            # GET /malware.exe) — a multipart file upload to an allowed
            # path (POST /upload with a part named shell.php) sailed
            # straight through, since the uploaded file's own name was
            # never checked. FILES_NAMES is ModSecurity's per-part
            # filename collection from multipart parsing (SecRequestBody
            # Access On, already set in modsecurity.conf) — populated
            # regardless of SecUploadDir, which only controls whether the
            # file's *content* gets persisted to disk (that's a separate,
            # not-yet-built capability — AV/malware scanning — not needed
            # just to read a filename). phase:2 because the request body
            # (where multipart parts live) isn't parsed yet at phase:1.
            config_lines.append(
                f'SecRule FILES_NAMES "@rx {ext_pattern}" '
                f'"id:5900005,phase:2,deny,status:403,log,t:lowercase,'
                f"msg:'Restricted file extension in uploaded file blocked by Positive Security policy'\""
            )
            config_lines.append("")

        config_content = "\n".join(config_lines) + "\n"
        logger.info(
            f"Generated Positive Security policy for {POSITIVE_SECURITY_CONF_PATH} "
            f"({len(allowed_methods)} allowed methods, {len(allowed_content_types)} allowed "
            f"content-types, {len(restricted_extensions)} restricted extensions), "
            "validating before apply..."
        )
        return write_and_apply_configs({POSITIVE_SECURITY_CONF_PATH: config_content})
    except Exception as e:
        logger.error(f"Failed to apply positive security settings: {e}")
        return False, str(e)


def apply_malware_scanning_settings(settings: dict) -> tuple[bool, str]:
    """
    Generates the @inspectFile SecRule (malware-scan.conf) AND its target
    script (malware-scan.sh) together, atomically, via one
    write_and_apply_configs() call — they must never drift out of sync
    (a .conf referencing a stale/missing script, or vice versa). Disabled
    by default: writes a comment-only .conf when settings["enabled"] is
    False, same convention as apply_positive_security_settings(), which
    correctly removes any previously-active rule.

    ModSecurity's SecUploadDir/SecUploadKeepFiles/SecUploadFileMode are
    static directives in modsecurity.conf (not toggle-driven — see that
    file's comment) — harmless when this feature is disabled, since
    nothing reads the uploaded-file temp path unless the @inspectFile
    rule generated here actually exists.

    The fail-open/fail-closed decision for a ClamAV-unreachable scan is
    baked directly into the generated script text (not read from a
    separate runtime config by the script itself) — see the fail_mode
    branch below. clamdscan's own exit-code convention: 0 = clean,
    1 = infected, 2 = scan error (can't connect, timed out, etc.) — only
    exit code 1 means "this file is actually infected"; anything else
    routes through the configured fail_mode instead of being treated as
    a detection.

    @inspectFile's own contract: the script's STDOUT is the match value —
    EMPTY stdout (regardless of exit code, though we always exit 0 on the
    non-match paths for clarity) means no match (upload allowed); ANY
    stdout content means the rule matches (upload blocked, logged with
    that text).
    """
    try:
        enabled = bool(settings.get("enabled", False))
        conf_lines = [
            "# Auto-generated by CyberSentinel WAF GUI — Malware Scanning policy (P1-10)",
            "# Do not edit manually",
        ]

        if not enabled:
            conf_lines.append("# Malware scanning is currently disabled — no active rules.")
            conf_content = "\n".join(conf_lines) + "\n"
            # No script needed while disabled, but write an inert placeholder
            # anyway rather than leaving a stale executable scanner script on
            # disk from a previous "enabled" state — matches "absence never
            # silently keeps old behavior alive" elsewhere in this codebase.
            script_content = (
                "#!/bin/sh\n"
                "# Malware scanning is disabled — this script should never be invoked\n"
                "# (no @inspectFile rule references it while disabled).\n"
                "exit 0\n"
            )
            logger.info("Malware scanning is disabled — applying an empty policy.")
            ok, err = write_and_apply_configs({
                MALWARE_SCAN_CONF_PATH: conf_content,
                MALWARE_SCAN_SCRIPT_PATH: script_content,
            })
            if ok:
                try:
                    # Standard rwxr-xr-x for a script ModSecurity's @inspectFile
                    # hook must be able to execute — not world-writable, contains no
                    # secrets.
                    os.chmod(MALWARE_SCAN_SCRIPT_PATH, 0o755)  # nosec B103
                except OSError as e:
                    logger.warning(f"Failed to chmod malware-scan.sh: {e}")
            return ok, err

        fail_mode = settings.get("fail_mode", "open")
        timeout_seconds = int(settings.get("scan_timeout_seconds", 5))

        if fail_mode == "closed":
            fallback_branch = (
                '        echo "AV scan unavailable (ClamAV unreachable or timed out) — '
                'blocked per fail-closed policy"\n'
                "        exit 1"
            )
        else:
            fallback_branch = (
                "        # ClamAV unreachable/timed out — fail OPEN per configured\n"
                "        # policy: allow the upload through rather than blocking every\n"
                "        # protected app's uploads during a scanner outage. Change to\n"
                "        # fail-closed in Settings > Hardening if this deployment needs\n"
                "        # the stricter guarantee instead.\n"
                "        exit 0"
            )

        script_content = (
            "#!/bin/sh\n"
            "# Auto-generated by CyberSentinel WAF GUI — ClamAV scan wrapper for\n"
            "# ModSecurity's @inspectFile operator (P1-10). Do not edit manually.\n"
            "#\n"
            "# Invoked by ModSecurity as: $0 <path-to-uploaded-file-part>\n"
            'FILE="$1"\n'
            "\n"
            f'RESULT=$(timeout {timeout_seconds} clamdscan --no-summary --infected --stream "$FILE" 2>/dev/null)\n'
            "STATUS=$?\n"
            "\n"
            'if [ "$STATUS" -eq 0 ]; then\n'
            "    exit 0\n"
            'elif [ "$STATUS" -eq 1 ]; then\n'
            '    echo "Malware detected: $RESULT"\n'
            "    exit 1\n"
            "else\n"
            f"{fallback_branch}\n"
            "fi\n"
        )

        conf_lines.extend([
            "",
            f'SecRule FILES_TMPNAMES "@inspectFile {MALWARE_SCAN_SCRIPT_PATH}" '
            f'"id:5910001,phase:2,block,t:none,log,'
            f"msg:'Malware detected in uploaded file (ClamAV)',severity:'CRITICAL',"
            f"tag:'malware',tag:'av-scan'\"",
            "",
        ])
        conf_content = "\n".join(conf_lines) + "\n"

        logger.info(
            f"Generated malware-scanning policy for {MALWARE_SCAN_CONF_PATH} "
            f"(fail_mode={fail_mode}, timeout={timeout_seconds}s), validating before apply..."
        )
        ok, err = write_and_apply_configs({
            MALWARE_SCAN_CONF_PATH: conf_content,
            MALWARE_SCAN_SCRIPT_PATH: script_content,
        })
        if ok:
            try:
                # See the other chmod(..., 0o755) above for why this is fine.
                os.chmod(MALWARE_SCAN_SCRIPT_PATH, 0o755)  # nosec B103
            except OSError as e:
                logger.warning(f"Failed to chmod malware-scan.sh: {e}")
        return ok, err
    except Exception as e:
        logger.error(f"Failed to apply malware scanning settings: {e}")
        return False, str(e)


def apply_api_schema_settings(domain: str, api_schema_json: str, mode: str) -> tuple[bool, str]:
    """
    Pushes one protected app's positive-security API schema into Redis —
    zero-reload, same pattern as apply_hardening_settings/apply_geo_block_
    settings above. Keyed by domain (not app_id) because that's what
    ml_check.lua's schema_validate module has cheaply available at request
    time via $host, with no need for an app_id lookup from Lua.

    api_schema_json is expected to already be validated JSON (see
    routes/apps.py's schema endpoint) shaped like:
        {"endpoints": [{"method": "POST", "path": "/api/users",
                         "required_fields": [...], "allowed_fields": [...]}]}
    A None/empty api_schema_json clears the key — enforcement in Lua is a
    no-op whenever nothing is stored for a given host, matching Positive
    Security's "absence never means deny-all" convention.
    """
    try:
        r = get_redis_client()
        key = f"waf:schema:{domain.strip().lower()}"
        if not api_schema_json:
            r.delete(key)
            logger.info(f"Cleared API schema for domain '{domain}'.")
            return True, ""

        import json as _json
        stored = _json.dumps({"mode": mode, **_json.loads(api_schema_json)})
        r.set(key, stored)
        logger.info(f"Successfully updated API schema in Redis for domain '{domain}' (mode={mode}).")
        return True, ""
    except Exception as e:
        logger.error(f"Failed to apply API schema settings for domain '{domain}': {e}")
        return False, str(e)


def apply_custom_response_page(html_content: str) -> tuple[bool, str]:
    """
    Writes the admin-configured "WAF blocked you" page to
    CUSTOM_RESPONSE_PAGE_PATH. The file itself is inert until a protected
    app's server{} block references it via an `internal` location (added in
    sync_protected_apps_to_nginx()) — that's what makes this actually get
    served on a real 403 instead of just sitting on disk.

    Uses write_and_apply_configs() purely for the atomic-write + validate +
    reload guarantee every other config writer here gets, even though nginx
    syntax validation has nothing to check in a plain HTML file — the value
    is the same backup/rollback-on-failure behavior and cache-busting reload.
    """
    try:
        return write_and_apply_configs({CUSTOM_RESPONSE_PAGE_PATH: html_content})
    except Exception as e:
        logger.error(f"Failed to apply custom response page: {e}")
        return False, str(e)


def app_auth_conf_path(app_id) -> str:
    return f"{APP_AUTH_CONF_DIR}/app_{app_id}.conf"


def app_cache_dir(app_id) -> str:
    return f"{APP_CACHE_BASE_DIR}/app_{app_id}"


def app_cache_zone_name(app_id) -> str:
    return f"cache_app_{app_id}"


def app_mtls_ca_path(app_id) -> str:
    return f"{APP_MTLS_CA_DIR}/app_{app_id}_ca.pem"


def _generate_app_auth_conf(app: dict) -> str:
    """
    Generates a ModSecurity rule denying (401) any request missing a
    configured header or cookie — a PRESENCE check, not token validation
    (the token isn't verified, just that something was sent). Comment-only
    when require_auth is off, same "always reference the file, content
    decides" pattern as apply_positive_security_settings().
    """
    lines = [
        "# Auto-generated by CyberSentinel WAF GUI — per-app auth requirement",
        "# Do not edit manually",
    ]

    if not app.get("require_auth"):
        lines.append("# Authentication requirement is disabled for this app — no active rules.")
        return "\n".join(lines) + "\n"

    check_type = app.get("auth_check_type") or "header"
    raw_name = (app.get("auth_header_name") or "Authorization").strip()
    # Header/cookie names are restricted to token characters (RFC 7230) —
    # stripping anything else both sanitizes for safe embedding in the
    # ModSecurity variable name and rejects nonsense input safely.
    safe_name = re.sub(r"[^A-Za-z0-9!#$%&'*+\-.^_`|~]", "", raw_name) or "Authorization"

    variable = f"REQUEST_COOKIES:{safe_name}" if check_type == "cookie" else f"REQUEST_HEADERS:{safe_name}"
    app_id = app.get("id")

    lines.append(
        f'SecRule &{variable} "@eq 0" '
        f'"id:{5_910_000 + int(app_id)},phase:1,deny,status:401,log,'
        f"msg:'Request missing required authentication'\""
    )
    return "\n".join(lines) + "\n"


def _sanitize_config_comment(value: str) -> str:
    """Makes an arbitrary stored string safe to interpolate into a generated
    nginx `#` comment line.

    Strips every control character (newline included — that is the one that
    matters: a newline ends the comment and everything after it is parsed as
    real nginx configuration) plus the metacharacters that would let a value
    read as nginx syntax if it is ever interpolated outside a comment. Falls
    back to a placeholder rather than an empty string so the generated comment
    never collapses into a bare "# --- Upstream App 7:  () ---".
    """
    cleaned = "".join(
        ch for ch in (value or "")
        if ord(ch) >= 0x20 and ord(ch) != 0x7F and ch not in "{};#\\"
    ).strip()
    return cleaned[:64] or "unnamed"


def sync_protected_apps_to_nginx() -> tuple[bool, str]:
    """
    Generates NGINX virtual host configurations for all active protected applications
    and reloads NGINX.
    """
    from app.services.db_service import get_all_protected_apps
    from app.services.settings_manager import settings_manager

    try:
        apps = get_all_protected_apps()
        active_apps = [app for app in apps if app.get("is_active", 1) == 1]

        # Server Cloaking (Settings > Hardening) previously only set
        # `server_tokens off` — which strips nginx's OWN version string, but
        # does nothing about headers the PROTECTED APP'S OWN BACKEND sets,
        # since proxy_pass forwards arbitrary upstream response headers
        # verbatim by default. Confirmed live against a real deployed app:
        # `X-Powered-By: Express` reached the client unchanged even with
        # cloaking on. (nginx does NOT forward the upstream's own `Server`/
        # `Date` headers by default — those are always its own — so only
        # arbitrary custom headers like this actually need hiding here.)
        hardening = settings_manager.get_hardening()
        server_cloaking = bool(hardening.get("server_cloaking", True))
        cloaking_hide_headers = [
            "X-Powered-By", "X-AspNet-Version", "X-AspNetMvc-Version",
            "X-Runtime", "X-Generator",
        ]

        # 1. Generate dynamic rate limit zones file in /etc/nginx/conf.d/
        rate_limit_lines = [
            "# Auto-generated by CyberSentinel WAF GUI",
            "# Per-application rate limit zones definition",
            ""
        ]
        
        for app in active_apps:
            app_id = app.get("id")
            rate_rps = app.get("rate_limit_rps", 50)
            rate_limit_lines.append(
                f"limit_req_zone $binary_remote_addr zone=zone_app_{app_id}:10m rate={rate_rps}r/s;"
            )
            
        rate_limits_content = "\n".join(rate_limit_lines) + "\n"
        rate_limits_conf_path = "/etc/nginx/conf.d/waf_app_rate_limits.conf"

        config_lines = [
            "# =============================================================================",
            "# Dynamic WAF Protected Applications — Virtual Host Configuration",
            "# Auto-generated by CyberSentinel WAF GUI",
            "# Do not edit manually",
            "# =============================================================================",
            "",
            "# Port 80: ACME HTTP-01 challenge passthrough + HTTPS redirect",
            "server {",
            "    listen 80 default_server;",
            "    listen [::]:80 default_server;",
            "    server_name _;",
            "    access_log /var/log/nginx/http_redirect.log combined;",
            "",
            "    # Let's Encrypt HTTP-01 challenge: serve webroot, do NOT redirect",
            "    location /.well-known/acme-challenge/ {",
            "        root /etc/nginx/acme-challenge;",
            "        default_type text/plain;",
            "        try_files $uri =404;",
            "    }",
            "",
            "    # All other traffic: redirect to HTTPS",
            "    location / {",
            "        return 301 https://$host$request_uri;",
            "    }",
            "}",
            ""
        ]

        # Populated per-app inside the loop below; must exist regardless of
        # which branch runs so the final write_and_apply_configs() call
        # (outside both branches) can always reference it.
        app_auth_files = {}

        # proxy_cache_path lines for apps with response caching enabled —
        # must live at the http{} context (this file is include'd from
        # nginx.conf's http block, same as waf_app_rate_limits.conf), so
        # they're collected here rather than emitted inline per server{}.
        cache_zone_lines = [
            "# Auto-generated by CyberSentinel WAF GUI",
            "# Per-application response-cache zone definitions",
            "",
        ]

        if not active_apps:
            logger.warning("No active protected applications found in database. Generating fallback server block.")
            config_lines.extend([
                "# Fallback dummy server when no apps are active",
                "server {",
                "    listen 443 ssl default_server;",
                "    listen [::]:443 ssl default_server;",
                "    http2 on;",
                "    server_name _;",
                "",
                "    ssl_certificate     /etc/nginx/ssl/cybersentinel.crt;",
                "    ssl_certificate_key /etc/nginx/ssl/cybersentinel.key;",
                "",
                # JA4 capture — see the identical line + comment on the
                # real per-app server block below for the full story (a
                # confirmed live outage: this used to be one global
                # http-level directive in nginx.conf, which every server
                # block inherits — including the plain-HTTP :3020
                # dashboard vhost with no `listen ... ssl` at all, which
                # made nginx refuse the whole config with "no ssl
                # configured for the server"). Emitted only here, inside a
                # confirmed `listen 443 ssl` block, never globally.
                "    ssl_client_hello_by_lua_file /opt/ml-waf/ja4_entry.lua;",
                "",
                # Only ever emitted inside a `listen 443 ssl` block — this
                # generator never puts it on a plain-HTTP server{}, unlike
                # the bug fixed globally in nginx.conf/main.py (see those
                # for why HSTS on a plain-HTTP response is dangerous: it's
                # host-scoped, not port-scoped, and poisons every other
                # port on this host too, including the SSO-critical :3020
                # admin dashboard).
                "    add_header Strict-Transport-Security \"max-age=31536000; includeSubDomains\" always;",
                "",
                "    location / {",
                "        default_type text/html;",
                "        return 404 \"<html><head><title>No Protected Applications</title></head><body style='font-family:sans-serif; text-align:center; padding:50px; background:#0b0f19; color:#f3f4f6;'><h2>CyberSentinel WAF</h2><p style='color:#9ca3af;'>No active protected applications are currently routed through this gateway.</p></body></html>\";",
                "    }",
                "}"
            ])
        else:
            has_wildcard_default = any(app.get("domain") == "_" for app in active_apps)

            for app in active_apps:
                app_id = app.get("id")
                # Defence in depth against config injection. routes/apps.py's
                # validate_name() already rejects control characters and nginx
                # metacharacters on the way in, but this generator is the last
                # thing standing between a stored value and the running gateway
                # config, and it also renders rows written before that
                # validator existed (or by any future write path that forgets
                # it). `name` is emitted into "# --- ..." comment lines below;
                # a newline here would end the comment and turn the rest of the
                # value into live nginx directives.
                name = _sanitize_config_comment(app.get("name") or f"App {app_id}")
                domain = app.get("domain", "_").strip().lower()
                upstream_host = app.get("upstream_host", "host.docker.internal").strip()
                upstream_port = app.get("upstream_port", 7000)
                protocol = app.get("protocol", "http").strip().lower()
                burst = app.get("burst_tolerance", 100)

                # Multi-server load balancing (P1-14, simplest version):
                # the primary upstream_host/upstream_port plus any extra
                # origins configured for this app. additional_origins is
                # stored as a JSON array string (see db_service.py) —
                # NULL/empty/malformed all degrade to "no extra origins",
                # never a 500, since a corrupt value here must not be able
                # to take down this app's whole nginx config generation.
                extra_origins = []
                raw_extra = app.get("additional_origins")
                if raw_extra:
                    try:
                        parsed = json.loads(raw_extra)
                        if isinstance(parsed, list):
                            extra_origins = [
                                o for o in parsed
                                if isinstance(o, dict) and o.get("host") and o.get("port")
                            ]
                    except (json.JSONDecodeError, TypeError):
                        logger.warning(f"App {app_id}: malformed additional_origins, ignoring: {raw_extra!r}")
                
                # Decide if default_server is applied. Only an app explicitly
                # configured with domain == "_" may become the catch-all for
                # unrecognized Host headers — previously the first active app
                # silently became default_server whenever no app had opted in
                # as "_", so any request with an unmatched Host header reached
                # a real customer's backend instead of a generic reject (see
                # the dedicated fallback block appended after this loop).
                is_default = domain == "_"

                listen_suffix = " default_server" if is_default else ""
                
                # Determine which cert to use for this app
                ssl_option = app.get("ssl_option", "self-signed")
                ssl_cert_path = app.get("ssl_cert_path") or ""
                ssl_key_path  = app.get("ssl_key_path")  or ""

                # Validate that the configured cert files actually exist on disk;
                # fall back to the default self-signed cert if they are missing.
                DEFAULT_CERT = "/etc/nginx/ssl/cybersentinel.crt"
                DEFAULT_KEY  = "/etc/nginx/ssl/cybersentinel.key"

                if ssl_option in ("letsencrypt", "custom") and ssl_cert_path and ssl_key_path:
                    if os.path.exists(ssl_cert_path) and os.path.exists(ssl_key_path):
                        active_cert = ssl_cert_path
                        active_key  = ssl_key_path
                    else:
                        logger.warning(
                            f"App {app_id} ({domain}): configured cert not found at {ssl_cert_path}. "
                            "Falling back to self-signed cert."
                        )
                        active_cert = DEFAULT_CERT
                        active_key  = DEFAULT_KEY
                else:
                    active_cert = DEFAULT_CERT
                    active_key  = DEFAULT_KEY

                auth_conf_path = app_auth_conf_path(app_id)
                app_auth_files[auth_conf_path] = _generate_app_auth_conf(app)

                # Basic response caching (roadmap item), opt-in per app.
                response_cache_enabled = bool(app.get("enable_response_cache", 0))
                if response_cache_enabled:
                    cache_dir = app_cache_dir(app_id)
                    # Created here (backend container), not by nginx itself
                    # at startup — the openresty container's master process
                    # is a separate filesystem this code can't otherwise
                    # reach. 0o777 is deliberate, not an oversight: this
                    # directory only ever holds cached PUBLIC response
                    # bodies (nginx's own Set-Cookie/GET-HEAD-only defaults,
                    # left untouched below, already keep personalized
                    # responses out of it) — not secrets, unlike e.g.
                    # /var/modsecurity/uploads' 0o700 — so there's no
                    # meaningful exposure from both containers' worker
                    # processes (potentially different uids) being able to
                    # write into it.
                    os.makedirs(cache_dir, exist_ok=True)
                    os.chmod(cache_dir, 0o777)  # nosec B103 — see comment above
                    cache_zone_lines.append(
                        f"proxy_cache_path {cache_dir} levels=1:2 "
                        f"keys_zone={app_cache_zone_name(app_id)}:10m "
                        f"max_size=200m inactive=60m use_temp_path=off;"
                    )

                # mTLS for API auth (roadmap item), opt-in per app, scoped
                # to /api only — see ml_check.lua's check_mtls(). Requires
                # BOTH the DB toggle AND an actually-uploaded CA cert file
                # still present on disk; a toggle left on after the cert
                # was somehow removed must never silently request a client
                # cert against a nonexistent CA file (nginx would refuse
                # to start entirely — exactly tonight's other outage
                # class), so this fails closed to "mTLS not applied" if
                # the file is missing, not just "trust the DB flag".
                mtls_ca_cert_path = app.get("mtls_ca_cert_path")
                mtls_active = bool(app.get("mtls_enabled", 0)) and bool(mtls_ca_cert_path) and os.path.exists(mtls_ca_cert_path)
                mtls_mode = app.get("mtls_mode") or "log"
                if mtls_mode not in ("log", "enforce"):
                    mtls_mode = "log"

                upstream_server_lines = [f"    server {upstream_host}:{upstream_port} max_fails=3 fail_timeout=10s;"]
                for origin in extra_origins:
                    upstream_server_lines.append(
                        f"    server {str(origin['host']).strip()}:{origin['port']} max_fails=3 fail_timeout=10s;"
                    )

                config_lines.extend([
                    f"# --- Upstream App {app_id}: {name} ({domain}) ---",
                    f"upstream upstream_app_{app_id} {{",
                    *upstream_server_lines,
                    "}",
                    "",
                    f"# --- App {app_id}: {name} ({domain}) [{ssl_option}] ---",
                    "server {",
                    f"    listen 443 ssl{listen_suffix};",
                    f"    listen [::]:443 ssl{listen_suffix};",
                    "    http2 on;",
                    f"    server_name {domain};",
                    "",
                    f"    ssl_certificate     {active_cert};",
                    f"    ssl_certificate_key {active_key};",
                    "",
                    # JA4 TLS-client fingerprint capture (ja4.lua via
                    # ja4_entry.lua) — deliberately scoped HERE, per
                    # SSL-terminating server block, NOT as a global
                    # http-level directive in nginx.conf. It used to be
                    # global, and that caused a real, confirmed outage:
                    # every server block inherits an http-level directive,
                    # including the plain-HTTP :3020 dashboard vhost (no
                    # `listen ... ssl` at all) — nginx refused the ENTIRE
                    # config at startup with "no ssl configured for the
                    # server" because the SSL-handshake-phase hook got
                    # merged onto a listen socket that never does TLS.
                    # lua-nginx-module documents this directive as valid in
                    # `http, server, location` context, so moving it to
                    # just the real SSL blocks (this one, plus the two
                    # fallback SSL blocks above/below) is fully supported —
                    # it just needed to not be global. See ja4.lua's header
                    # for what capture itself does.
                    "    ssl_client_hello_by_lua_file /opt/ml-waf/ja4_entry.lua;",
                    "",
                    # mTLS for API auth — ssl_verify_client can only be set
                    # at server (or http) level, never per-location, since
                    # certificate verification happens during the TLS
                    # handshake itself, before nginx knows which location
                    # the request is for. `optional` REQUESTS a client cert
                    # on every connection to this server block (not just
                    # /api) but never rejects a connection for lacking one
                    # at the TLS layer — the actual /api-only enforcement
                    # happens in ml_check.lua's check_mtls(), which reads
                    # $ssl_client_verify (always a safe built-in nginx
                    # variable, unlike the custom $waf_mtls_mode below) and
                    # the mode this `set` exposes to it.
                    *([
                        f"    ssl_client_certificate {mtls_ca_cert_path};",
                        "    ssl_verify_client optional;",
                        "    ssl_verify_depth 2;",
                        f'    set $waf_mtls_mode "{mtls_mode}";',
                        "",
                    ] if mtls_active else []),
                    # Only ever emitted inside a `listen 443 ssl` block —
                    # see the fallback block above for why this must never
                    # appear on a plain-HTTP server{}.
                    "    add_header Strict-Transport-Security \"max-age=31536000; includeSubDomains\" always;",
                    "",
                    "    resolver 127.0.0.11 valid=30s ipv6=off;",
                    "",
                    # Scoped to this protected app's own server block only —
                    # never the WAF GUI's own dashboard (a separate vhost on
                    # port 3020 that doesn't reference this file). Content is
                    # comment-only when Positive Security is disabled, so
                    # this reference is always safe to include.
                    f"    modsecurity_rules_file {POSITIVE_SECURITY_CONF_PATH};",
                    f"    modsecurity_rules_file {MALWARE_SCAN_CONF_PATH};",
                    f"    modsecurity_rules_file {auth_conf_path};",
                    "",
                    # Admin-configurable block page (Settings > Custom Response).
                    # Only overrides the browser-facing `/` location below —
                    # /api keeps its own JSON error_page, which is location-
                    # scoped and so takes precedence for requests under /api.
                    "    error_page 403 /__waf_block_page__.html;",
                    "    location = /__waf_block_page__.html {",
                    "        internal;",
                    f"        alias {CUSTOM_RESPONSE_PAGE_PATH};",
                    "        default_type text/html;",
                    "        sub_filter_types text/html;",
                    "        sub_filter '{{transaction_id}}' $request_id;",
                    "        sub_filter_once off;",
                    "    }",
                    "",
                    "    location @json_forbidden {",
                    "        default_type application/json;",
                    "        add_header Content-Type 'application/json; charset=utf-8' always;",
                    "        return 403 '{\"error\": \"🚨 WAF caught you! This attack has been blocked 🚫 and logged 📋. CyberSentinel is watching 👀\", \"code\": 403}';",
                    "    }",
                    "",
                    # Public locations dispatch to ml_decide.lua (CONTENT phase)
                    # instead of proxy_pass directly. That's the fix for a real,
                    # confirmed bug: ml_check.lua's own access_by_lua_file can't
                    # reliably read the CRS score, because nginx doesn't
                    # guarantee its (static) handler runs after
                    # ngx_http_modsecurity_module's (dynamically loaded)
                    # handler within the same access phase — but nginx DOES
                    # guarantee the whole access phase completes before the
                    # content phase starts. ml_decide.lua reads the score
                    # there and, on allow, hands off via ngx.exec() (internal
                    # redirect — same mechanism `error_page 403 =
                    # @json_forbidden` below already uses) to the named
                    # location's own proxy_pass, so headers/streaming/
                    # WebSocket upgrade/body forwarding are all still native
                    # nginx proxy behavior, unchanged.
                    "    location / {",
                    f"        limit_req zone=zone_app_{app_id} burst={burst};",
                    # Pulls in the DDoS/bot zones. Without this they are
                    # inert here: the limit_req directive above REPLACES
                    # every http-level one rather than adding to it
                    # (audit finding P1-04).
                    f"        include {DDOS_LIMITS_INCLUDE_PATH};",
                    f"        set $waf_upstream_location \"@proxy_app_{app_id}\";",
                    "        content_by_lua_file /opt/ml-waf/ml_decide.lua;",
                    "    }",
                    "",
                    "    location /api {",
                    "        error_page 403 = @json_forbidden;",
                    f"        limit_req zone=zone_app_{app_id} burst={max(5, burst // 3)} nodelay;",
                    f"        include {DDOS_LIMITS_INCLUDE_PATH};",
                    f"        set $waf_upstream_location \"@proxy_app_{app_id}\";",
                    "        content_by_lua_file /opt/ml-waf/ml_decide.lua;",
                    "    }",
                    "",
                    f"    location @proxy_app_{app_id} {{",
                    f"        proxy_pass {protocol}://upstream_app_{app_id};",
                    "        proxy_http_version 1.1;",
                    "        proxy_set_header Upgrade $http_upgrade;",
                    "        proxy_set_header Connection 'upgrade';",
                    "        proxy_set_header Host $host;",
                    "        proxy_set_header X-Real-IP $remote_addr;",
                    "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
                    "        proxy_set_header X-Forwarded-Proto $scheme;",
                    "        proxy_next_upstream error timeout http_502 http_503;",
                    "        proxy_next_upstream_tries 3;",
                    "        proxy_next_upstream_timeout 10s;",
                    *([f"        proxy_hide_header {h};" for h in cloaking_hide_headers] if server_cloaking else []),
                    # Basic response caching (roadmap item), opt-in per app
                    # above. Deliberately does NOT set proxy_ignore_headers
                    # or proxy_cache_bypass — nginx's own defaults already
                    # refuse to cache a response carrying Set-Cookie, and
                    # only ever cache GET/HEAD requests in the first place,
                    # which is exactly the safety this needs (never serve
                    # one client's personalized/authenticated response body
                    # to another). proxy_cache_valid only supplies a
                    # fallback duration for a response that doesn't specify
                    # its own Cache-Control/Expires — an origin's explicit
                    # "no-store" is still honored, this can't override it.
                    # X-Cache-Status is diagnostic only (HIT/MISS/BYPASS/
                    # EXPIRED), same idea as Cloudflare's own cf-cache-status.
                    *([
                        f"        proxy_cache {app_cache_zone_name(app_id)};",
                        "        proxy_cache_valid 200 302 10m;",
                        "        proxy_cache_valid 404 1m;",
                        "        add_header X-Cache-Status $upstream_cache_status always;",
                    ] if response_cache_enabled else []),
                    "    }",
                    "}",
                    ""
                ])

            if not has_wildcard_default:
                # No app opted in as the explicit wildcard ("_") — generic
                # reject for unrecognized Host headers instead of silently
                # picking one real app to expose (see the is_default comment
                # above). 444 is nginx's close-the-connection-with-no-response
                # code, already this WAF's convention for silent rejects
                # (waf_ddos.conf's limit_req_status/limit_conn_status).
                config_lines.extend([
                    "# Fallback catch-all: no app is configured as the explicit wildcard ('_')",
                    "# default, so unrecognized Host headers get a generic reject instead of",
                    "# reaching a real customer's backend.",
                    "server {",
                    "    listen 443 ssl default_server;",
                    "    listen [::]:443 ssl default_server;",
                    "    http2 on;",
                    "    server_name _;",
                    "",
                    "    ssl_certificate     /etc/nginx/ssl/cybersentinel.crt;",
                    "    ssl_certificate_key /etc/nginx/ssl/cybersentinel.key;",
                    "",
                    # JA4 capture — see the per-app server block's comment
                    # above for the full outage story. Emitted here too
                    # since this fallback also terminates real SSL.
                    "    ssl_client_hello_by_lua_file /opt/ml-waf/ja4_entry.lua;",
                    "",
                    # Only ever emitted inside a `listen 443 ssl` block —
                    # see the no-active-apps fallback above for why.
                    "    add_header Strict-Transport-Security \"max-age=31536000; includeSubDomains\" always;",
                    "",
                    "    location / {",
                    "        return 444;",
                    "    }",
                    "}",
                    ""
                ])

        config_content = "\n".join(config_lines) + "\n"
        apps_conf_path = "/etc/nginx/sites-enabled/mssp"
        cache_zones_content = "\n".join(cache_zone_lines) + "\n"

        logger.info(
            f"Generated dynamic WAF apps config for {apps_conf_path} "
            f"({len(active_apps)} active app(s)), validating before apply..."
        )
        return write_and_apply_configs({
            rate_limits_conf_path: rate_limits_content,
            APP_CACHE_ZONES_CONF_PATH: cache_zones_content,
            apps_conf_path: config_content,
            **app_auth_files,
        })
    except Exception as e:
        logger.error(f"Failed to sync protected apps to NGINX: {e}")
        return False, str(e)


def test_nginx_config() -> tuple[bool, str]:
    """
    Runs syntax check on NGINX/OpenResty configuration (openresty -c /etc/nginx/nginx.conf -t).
    Returns (True, "") if syntax is valid, or (False, error_details) otherwise.
    """
    candidates = [
        # Docker syntax test variants
        ["docker", "exec", "waf-openresty", "openresty", "-c", "/etc/nginx/nginx.conf", "-t"],
        ["docker", "exec", "waf-openresty", "nginx", "-c", "/etc/nginx/nginx.conf", "-t"],
        # sudo variants
        ["sudo", "/usr/local/openresty/bin/openresty", "-c", "/etc/nginx/nginx.conf", "-t"],
        ["sudo", "/usr/local/openresty/nginx/sbin/nginx", "-c", "/etc/nginx/nginx.conf", "-t"],
        # Direct variants
        ["/usr/local/openresty/bin/openresty", "-c", "/etc/nginx/nginx.conf", "-t"],
        ["/usr/local/openresty/nginx/sbin/nginx", "-c", "/etc/nginx/nginx.conf", "-t"],
        ["openresty", "-c", "/etc/nginx/nginx.conf", "-t"],
        ["nginx", "-c", "/etc/nginx/nginx.conf", "-t"],
    ]
    for cmd in candidates:
        try:
            result = subprocess.run(
                cmd, capture_output=True, text=True, timeout=10  # nosec B603
            )
            if result.returncode == 0:
                logger.info(f"NGINX/OpenResty config test passed via: {' '.join(cmd)}")
                return True, ""
            else:
                stderr = result.stderr or result.stdout or ""
                logger.warning(
                    f"Config test via '{' '.join(cmd)}' failed (rc={result.returncode}): "
                    f"{stderr.strip()}"
                )
                return False, stderr.strip()
        except FileNotFoundError:
            continue
        except subprocess.TimeoutExpired:
            logger.error(f"Config test command timed out: {' '.join(cmd)}")
            return False, "Syntax validation check timed out."
        except Exception as e:
            logger.error(f"Error testing config via '{' '.join(cmd)}': {e}")
            return False, str(e)
    logger.error("All NGINX/OpenResty configuration test attempts exhausted.")
    return False, "Could not run configuration syntax validation check."

